sxc-lib: ADC.h File Reference
ADC.h File Reference
Interface for configuring and reading data from the on-chip analog-to-digital converter.
#include "SystemClock.h"
Macros
#define ADC_CLK_RATE_DIV_2 (0x0 << 12)
#define ADC_CLK_RATE_DIV_4 (0x1 << 12)
#define ADC_CLK_RATE_DIV_8 (0x2 << 12)
#define ADC_CLK_RATE_DIV_16 (0x3 << 12)
#define ADC_CLK_RATE_DIV_32 (0x4 << 12)
#define ADC_CLK_RATE_DIV_64 (0x5 << 12)
#define ADC_CLK_RATE_DIV_128 (0x6 << 12)
#define ADC_CLK_RATE_DIV_256 (0x7 << 12)
#define ADC_ENABLE_FLOW_CONTROL (0x1 << 11)
#define ADC_CONT_SAMPLING (0x1 << 10)
#define ADC_SINGLE_CONV_SAMPLING (0x0 << 10)
#define ADC_THREE_CHANNEL_MODE (0x1 << 8)
#define ADC_FOUR_CHANNEL_MODE (0x0 << 8)
#define ADC_ON_BIT (0x1 << 15)
#define ADC_START_CONV_BIT (0x1 << 9)
#define ADC_CFG1_RESET_BIT (0x1 << 6)
Functions
SXC_INLINE void ADC_power_on (void)
Powers the ADC on. Does nothing if the ADC is already powered on. It is recommended to leave the ADC on only when necessary due to high power consumption.
SXC_INLINE void ADC_power_off (void)
Powers the ADC off. Does nothing if the ADC is already powered off.
SXC_INLINE void ADC_set_config (uint16_t cfg)
Configures the ADC based on the provided configuration, a bitwise-ORed set of ADCcfg0 flags.
SXC_INLINE uint16_t ADC_get_config (void)
Returns the ADC's current configuration.
SXC_INLINE void ADC_set_channel_nums (uint16_t const *nums)
Sets the 2-bit channel number(s) for the ADC to read from. Reads in 1 channel number if the ADC is in single conversion mode. If it is in continuous sampling mode, then as many channel numbers are read in as the ADC is configured for (3 or 4). Only the least significant 2 bits from each number are read; all others are ignored. No array boundary checking is done. Behaviour is unpredictable if the ADC is not configured before calling this function.
SXC_INLINE void ADC_set_clock_wait (uint16_t num_clocks)
Sets the 6-bit number of ADC clocks to wait for after a sample has been converted. This is only meaningful if the ADC is set for continuous sampling mode; this has no effect in single sampling mode.
SXC_INLINE uint16_t ADC_get_clock_wait (void)
Returns the ADC's current clock wait rate. This is only meaningful if the ADC is set for continuous sampling mode.
SXC_INLINE uint16_t ADC_read (void)
Reads a value measured by the ADC. If the flow control bit is enabled, a call to this function will block until sample conversion is complete.
Detailed Description
Interface for configuring and reading data from the on-chip analog-to-digital converter.
Definition in file ADC.h.
Macro Definition Documentation
#define ADC_CFG1_RESET_BIT (0x1 << 6)
Definition at line 36 of file ADC.h.
Referenced by ADC_power_on().
#define ADC_ON_BIT (0x1 << 15)
Definition at line 34 of file ADC.h.
Referenced by ADC_power_off(), and ADC_power_on().
#define ADC_START_CONV_BIT (0x1 << 9)
Definition at line 35 of file ADC.h.
Referenced by ADC_power_on().
Function Documentation
SXC_INLINE uint16_t ADC_get_clock_wait (void)
Returns the ADC's current clock wait rate. This is only meaningful if the ADC is set for continuous sampling mode.
Returns
Number of ADC clocks to wait on at the time of function call.
Definition at line 145 of file ADC.h.
References ADCcfg1, and mock_mem_map.
 {
 #ifndef __XINC2__
   return mock_mem_map[ADCcfg1]&0xFFC0;
 #else
   return _inp(ADCcfg1)&0xFFC0;
 #endif
 }
SXC_INLINE uint16_t ADC_get_config (void)
Returns the ADC's current configuration.
Returns
ADC's configuration at time of function call.
Definition at line 91 of file ADC.h.
References ADCcfg0, and mock_mem_map.
Referenced by ADC_set_channel_nums().
 {
 #ifndef __XINC2__
   return mock_mem_map[ADCcfg0];
 #else
   return _inp(ADCcfg0);
 #endif
 }
SXC_INLINE void ADC_power_off (void)
Powers the ADC off. Does nothing if the ADC is already powered off.
Definition at line 64 of file ADC.h.
References ADC_ON_BIT, ADCcfg0, and mock_mem_map.
 {
 #ifndef __XINC2__
   mock_mem_map[ADCcfg0] &= ~ADC_ON_BIT;
 #else
   _outp(_inp(ADCcfg0)&~ADC_ON_BIT, ADCcfg0);
 #endif
 }
SXC_INLINE void ADC_power_on (void)
Powers the ADC on. Does nothing if the ADC is already powered on. It is recommended to leave the ADC on only when necessary due to high power consumption.
Definition at line 43 of file ADC.h.
References ADC_CFG1_RESET_BIT, ADC_ON_BIT, ADC_START_CONV_BIT, ADCcfg0, ADCcfg1, and mock_mem_map.
 {
 #ifndef __XINC2__
   mock_mem_map[ADCcfg0] |= ADC_ON_BIT;
 #else
   uint16_t cfg0 = _inp(ADCcfg0)|ADC_ON_BIT;
   uint16_t cfg1 = _inp(ADCcfg1);
   _outp(cfg0, ADCcfg0);
   _outp(cfg0|ADC_START_CONV_BIT, ADCcfg0);
   _outp(cfg1|ADC_CFG1_RESET_BIT, ADCcfg1);
   //NOPs because ADC reset bit must be on for at least 3 clock cycles
   _nop();
   _nop();
   _nop();
   _outp(cfg1&~ADC_CFG1_RESET_BIT, ADCcfg1);
 #endif
 }
SXC_INLINE uint16_t ADC_read (void)
Reads a value measured by the ADC. If the flow control bit is enabled, a call to this function will block until sample conversion is complete.
Returns
Bits 9-0: the 10-bit value measured and converted by the ADC. Bits 14-13: the channel number of the sample Bit 15: if 1, the ADC is busy doing a conversion
Definition at line 161 of file ADC.h.
References ADCdata, and mock_mem_map.
 {
 #ifndef __XINC2__
   return mock_mem_map[ADCdata];
 #else
   return _inp(ADCdata);
 #endif
 }
SXC_INLINE void ADC_set_channel_nums (uint16_t const * nums) inline
Sets the 2-bit channel number(s) for the ADC to read from. Reads in 1 channel number if the ADC is in single conversion mode. If it is in continuous sampling mode, then as many channel numbers are read in as the ADC is configured for (3 or 4). Only the least significant 2 bits from each number are read; all others are ignored. No array boundary checking is done. Behaviour is unpredictable if the ADC is not configured before calling this function.
Parameters
[in] nums Pointer to desired sampling channel numbers
Definition at line 110 of file ADC.h.
References ADC_CONT_SAMPLING, ADC_get_config(), ADC_set_config(), and ADC_THREE_CHANNEL_MODE.
 {
   uint16_t cfg = ADC_get_config() & 0xFF00; //clear the channel nums
   size_t bound = (!(cfg & ADC_CONT_SAMPLING)) ? 1 :
                  (cfg & ADC_THREE_CHANNEL_MODE) ? 3 : 4;
   for (size_t i = 0; i < bound; ++i)
     cfg |= _rol( nums[i]&0x3, _rol(i,1) );
   ADC_set_config(cfg);
 }
SXC_INLINE void ADC_set_clock_wait (uint16_t num_clocks)
Sets the 6-bit number of ADC clocks to wait for after a sample has been converted. This is only meaningful if the ADC is set for continuous sampling mode; this has no effect in single sampling mode.
Parameters
[in] num_clocks Number of ADC clocks to wait before re-sampling. Only the least significant 6 bits are considered; all others are ignored.
Definition at line 127 of file ADC.h.
References ADCcfg1, and mock_mem_map.
 {
 #ifndef __XINC2__
   mock_mem_map[ADCcfg1] &= 0xFFC0;
   mock_mem_map[ADCcfg1] |= (num_clocks&0x003F);
 #else
   uint16_t cfg = _inp(ADCcfg1);
   cfg &= 0xFFC0;
   cfg |= (num_clocks&0x003F);
   _outp(cfg, ADCcfg1);
 #endif
 }
SXC_INLINE void ADC_set_config (uint16_t cfg)
Configures the ADC based on the provided configuration, a bitwise-ORed set of ADCcfg0 flags.
Parameters
[in] cfg Desired ADC configuration.
Definition at line 78 of file ADC.h.
References ADCcfg0, and mock_mem_map.
Referenced by ADC_set_channel_nums().
 {
 #ifndef __XINC2__
   mock_mem_map[ADCcfg0] = cfg;
 #else
   _outp(cfg, ADCcfg0);
 #endif
 }