sxc-lib: EEPROM.h File Reference
EEPROM.h File Reference
Interface for interacting with an EEPROM over SPI. The internal XInC2 EEPROM is available on SPI0, and users may connect additional ones on SPI1.
#include "SPI.h"
#include "Structs.h"
Enumerations
enum EepromCommands {
NOP = 0, WRITE = 2, READ = 3, WRITE_DISABLE = 4,
READ_STATUS_REGISTER = 5, WRITE_ENABLE = 6
}
Functions
SXC_INLINE void EEPROM_write_word (enum SPI_name spi, GlobalPin const *chip_select_pin, uint16_t *addr, uint16_t word)
Writes a 16-bit word to a memory address in an EEPROM on the designated SPI.
SXC_INLINE void EEPROM_write_byte (enum SPI_name spi, GlobalPin const *chip_select_pin, uint16_t *addr, uint16_t word)
Writes an 8-bit byte to a memory address in an EEPROM on the designated SPI.
SXC_INLINE uint16_t EEPROM_read_byte (enum SPI_name spi, GlobalPin const *chip_select_pin, uint16_t *addr)
Reads an 8-bit byte from a memory address in an EEPROM on the designated SPI.
SXC_INLINE uint16_t EEPROM_read_word (enum SPI_name spi, GlobalPin const *chip_select_pin, uint16_t *addr)
Reads a 16-bit word from a memory address in an EEPROM on the designated SPI.
Variables
GlobalPin const kInternalChipSelect = { GPIO_B, io_PB0, 0x1, Polar_ActiveLow }
const uint16_t kInternalRAMOffset = 0xC000
Detailed Description
Interface for interacting with an EEPROM over SPI. The internal XInC2 EEPROM is available on SPI0, and users may connect additional ones on SPI1.
Definition in file EEPROM.h.
Enumeration Type Documentation
enum EepromCommands
Enumerator
NOP
WRITE
READ
WRITE_DISABLE
READ_STATUS_REGISTER
WRITE_ENABLE
Definition at line 16 of file EEPROM.h.
                     {
   NOP = 0,
   WRITE = 2,
   READ = 3,
   WRITE_DISABLE = 4,
   READ_STATUS_REGISTER = 5,
   WRITE_ENABLE = 6,
 };
Function Documentation
SXC_INLINE uint16_t EEPROM_read_byte (enum SPI_name spi, GlobalPin const * chip_select_pin, uint16_t * addr)
Reads an 8-bit byte from a memory address in an EEPROM on the designated SPI.
Parameters
[in] spi Name of the SPI where the EEPROM is located: SPI0 always connects to the internal EEPROM
[in] chip_select_pin GlobalPin to which the EEPROM's chip select line is wired
[in] addr 16-bit memory address in the EEPROM to which to write the value
Returns
LSB: Raw 8-bit value read from the EEPROM MSB: undefined
Definition at line 109 of file EEPROM.h.
References globalPin_write(), OFF, ON, READ, SPI_read(), and SPI_write().
 {
   globalPin_write(ON, chip_select_pin);
   SPI_write((uint16_t)READ, spi);
   SPI_write((_rol((uint16_t)addr, 8)), spi);
   SPI_write((uint16_t)addr, spi);
   uint16_t value = SPI_read(spi);
   globalPin_write(OFF, chip_select_pin);
   return value;
 }
SXC_INLINE uint16_t EEPROM_read_word (enum SPI_name spi, GlobalPin const * chip_select_pin, uint16_t * addr)
Reads a 16-bit word from a memory address in an EEPROM on the designated SPI.
Parameters
[in] spi Name of the SPI where the EEPROM is located: SPI0 always connects to the internral EEPROM
[in] chip_select_pin GlobalPin to which the EEPROM's chip select line is wired
[in] addr 16-bit memory address in the EEPROM to which to write the value
Returns
Raw 16-bit value read from the EEPROM
Definition at line 132 of file EEPROM.h.
References globalPin_write(), OFF, ON, READ, SPI_read(), and SPI_write().
 {
   globalPin_write(ON, chip_select_pin);
   SPI_write((uint16_t)READ, spi);
   SPI_write((_rol((uint16_t)addr, 8)), spi);
   SPI_write((uint16_t)addr, spi);
   uint16_t value = SPI_read(spi);
   value |= _rol(SPI_read(spi), 8);
   globalPin_write(OFF, chip_select_pin);
   return value;
 }
SXC_INLINE void EEPROM_write_byte (enum SPI_name spi, GlobalPin const * chip_select_pin, uint16_t * addr, uint16_t word)
Writes an 8-bit byte to a memory address in an EEPROM on the designated SPI.
Parameters
[in] spi Name of the SPI where the EEPROM is located: SPI0 always connects to the internal EEPROM
[in] chip_select_pin GlobalPin to which the EEPROM's chip select line is wired
[in] addr 16-bit memory address in the EEPROM to which to write the value
[in] word LSB: Raw 8-bit value to write to the EEPROM MSB: undefined
Definition at line 74 of file EEPROM.h.
References globalPin_write(), OFF, ON, READ_STATUS_REGISTER, SPI_read(), SPI_write(), WRITE, and WRITE_ENABLE.
 {
   globalPin_write(ON, chip_select_pin);
   SPI_write((uint16_t)WRITE_ENABLE, spi);
   globalPin_write(OFF, chip_select_pin);
   globalPin_write(ON, chip_select_pin);
   SPI_write((uint16_t)WRITE, spi);
   SPI_write((_rol((uint16_t)addr, 8)), spi);
   SPI_write((uint16_t)addr, spi);
   SPI_write(word, spi);
   SPI_write((_rol(word, 8)), spi);
   globalPin_write(OFF, chip_select_pin);
   uint16_t writing = 1;
   while (writing) {
     globalPin_write(ON, chip_select_pin);
     SPI_write((uint16_t)READ_STATUS_REGISTER, spi);
     writing = SPI_read(spi) & 0x1;
     globalPin_write(OFF, chip_select_pin);
   }
 }
SXC_INLINE void EEPROM_write_word (enum SPI_name spi, GlobalPin const * chip_select_pin, uint16_t * addr, uint16_t word)
Writes a 16-bit word to a memory address in an EEPROM on the designated SPI.
Parameters
[in] spi Name of the SPI where the EEPROM is located: SPI0 always connects to the internal EEPROM
[in] chip_select_pin GlobalPin to which the EEPROM's chip select line is wired
[in] addr 16-bit memory address in the EEPROM to which to write the value
[in] word Raw 16-bit value to write to the EEPROM
Definition at line 39 of file EEPROM.h.
References globalPin_write(), OFF, ON, READ_STATUS_REGISTER, SPI_read(), SPI_write(), WRITE, and WRITE_ENABLE.
 {
   globalPin_write(ON, chip_select_pin);
   SPI_write((uint16_t)WRITE_ENABLE, spi);
   globalPin_write(OFF, chip_select_pin);
   globalPin_write(ON, chip_select_pin);
   SPI_write((uint16_t)WRITE, spi);
   SPI_write((_rol((uint16_t)addr, 8)), spi);
   SPI_write((uint16_t)addr, spi);
   SPI_write(word, spi);
   SPI_write((_rol(word, 8)), spi);
   globalPin_write(OFF, chip_select_pin);
   uint16_t writing = 1;
   while (writing) {
     globalPin_write(ON, chip_select_pin);
     SPI_write((uint16_t)READ_STATUS_REGISTER, spi);
     writing = SPI_read(spi) & 0x1;
     globalPin_write(OFF, chip_select_pin);
   }
 }
Variable Documentation
GlobalPin const kInternalChipSelect = { GPIO_B, io_PB0, 0x1, Polar_ActiveLow }
Definition at line 25 of file EEPROM.h.
const uint16_t kInternalRAMOffset = 0xC000
Definition at line 26 of file EEPROM.h.