sxc-lib: Semaphore.h File Reference
Semaphore.h File Reference
Semaphore-abstraction library for use with XInC2 processor. Provides single semaphore interface for all targets.
#include "SXC.h"
#include "register_consts.h"
#include <semaphore.h>
#include <errno.h>
Macros
#define kNumSemaphores 16
#define SEM_THRD 15
Functions
__attribute__ ((common)) sem_t mock_sems[kNumSemaphores]
SXC_INLINE void sem_init_all (void)
On POSIX targets, initializes all semaphores. Does nothing otherwise. MUST be called in main function on POSIX prior to using semaphores; otherwise, undefined behavior occurs.
SXC_INLINE void sem_destroy_all (void)
On POSIX targets, destroys all semaphores prior to array de-allocation/main exit to release OS resources properly. Does nothing for non-POSIX.
SXC_INLINE void sem_lock (uint16_t sem_num)
Locks the semaphore numbered "sem_num". Returns immediately if the semaphore is unlocked. Performs a blocking wait on the semaphore if it is already locked.
SXC_INLINE void sem_unlock (uint16_t sem_num)
Unlocks the semaphore numbered "sem_num". Always returns immediately. Does nothing if the semaphore is already unlocked.
SXC_INLINE void sem_unlock_all (void)
Unlocks all semaphores. It is recommended to never call this function.
SXC_INLINE void atomic_copy (void *dest, void *src, size_t num_bytes, uint16_t sem)
Performs an atomic assignment from src to dest by using a semaphore lock. Current pseudo-replacement for Atomic class.
Detailed Description
Semaphore-abstraction library for use with XInC2 processor. Provides single semaphore interface for all targets.
In the XInC2 and test harness cases, all function calls will be some variant of _inp or _outp. For other targets, we use POSIX. Although the XInC2 processor has 16 user-accessible semaphores, we will lock thread creation/destruction a dedicated leaving only 15 for users to use arbitrarily.
Definition in file Semaphore.h.
Macro Definition Documentation
#define kNumSemaphores 16
Definition at line 21 of file Semaphore.h.
Referenced by sem_destroy_all(), sem_init_all(), and sem_unlock_all().
#define SEM_THRD 15
Definition at line 22 of file Semaphore.h.
Referenced by thread_read_retval(), thread_run(), thread_setup(), thread_stop(), and thread_stoprun_multiple().
Function Documentation
__attribute__ ((common))
SXC_INLINE void atomic_copy (void * dest, void * src, size_t num_bytes, uint16_t sem)
Performs an atomic assignment from src to dest by using a semaphore lock. Current pseudo-replacement for Atomic class.
Parameters
[in] dest Destination address where to write data to
[in] src Source address where to read data from
[in] num_bytes Number of 16-bit (NOT 8-bit!) "bytes" to copy
[in] sem Semaphore to lock on
Definition at line 135 of file Semaphore.h.
References sem_lock(), and sem_unlock().
 {
   sem_lock(sem);
   size_t i;
   for (i=0; i<num_bytes; ++i)
     *((uint16_t*)dest+i) = *((uint16_t*)src+i);
   sem_unlock(sem);
 }
SXC_INLINE void sem_destroy_all (void)
On POSIX targets, destroys all semaphores prior to array de-allocation/main exit to release OS resources properly. Does nothing for non-POSIX.
Definition at line 69 of file Semaphore.h.
References kNumSemaphores.
 {
 #ifndef __XINC2__
   uint16_t i;
   for (i=0; i<kNumSemaphores; ++i)
     sem_destroy(mock_sems+i);
 #endif
   return;
 }
SXC_INLINE void sem_init_all (void)
On POSIX targets, initializes all semaphores. Does nothing otherwise. MUST be called in main function on POSIX prior to using semaphores; otherwise, undefined behavior occurs.
Definition at line 54 of file Semaphore.h.
References kNumSemaphores.
 {
 #ifndef __XINC2__
   uint16_t i;
   for (i=0; i<kNumSemaphores; ++i)
     sem_init(mock_sems+i, 0 /*no multi-process sem sharing*/, 1 /*mutex-like*/);
 #endif
   return;
 }
SXC_INLINE void sem_lock (uint16_t sem_num)
Locks the semaphore numbered "sem_num". Returns immediately if the semaphore is unlocked. Performs a blocking wait on the semaphore if it is already locked.
Parameters
[in] sem_num semaphore to lock
Definition at line 85 of file Semaphore.h.
References mock_mem_map, safe_mode_assert, and SCUdown.
Referenced by atomic_copy(), gpio_atomic_pin_set(), gpio_atomic_pin_unset(), thread_read_retval(), thread_run(), thread_setup(), thread_stop(), and thread_stoprun_multiple().
 {
   safe_mode_assert(sem_num < kNumSemaphores);
 #ifndef __XINC2__
   mock_mem_map[SCUdown] |= (1 << sem_num);
   sem_wait(mock_sems+sem_num);
   mock_mem_map[SCUdown] &= ~(1 << sem_num);
 #else
   _outp(_rol(1,sem_num), SCUdown);
 #endif
   return;
 }
SXC_INLINE void sem_unlock (uint16_t sem_num)
Unlocks the semaphore numbered "sem_num". Always returns immediately. Does nothing if the semaphore is already unlocked.
Parameters
[in] sem_num semaphore to unlock
Definition at line 103 of file Semaphore.h.
References mock_mem_map, safe_mode_assert, and SCUup.
Referenced by atomic_copy(), gpio_atomic_pin_set(), gpio_atomic_pin_unset(), sem_unlock_all(), thread_read_retval(), thread_run(), thread_setup(), thread_stop(), and thread_stoprun_multiple().
 {
   safe_mode_assert(sem_num < kNumSemaphores);
 #ifndef __XINC2__
   mock_mem_map[SCUup] |= (1 << sem_num);
   sem_post(mock_sems+sem_num);
   mock_mem_map[SCUup] &= ~(1 << sem_num);
 #else
   _outp(_rol(1,sem_num), SCUup);
 #endif
   return;
 }
SXC_INLINE void sem_unlock_all (void)
Unlocks all semaphores. It is recommended to never call this function.
Definition at line 119 of file Semaphore.h.
References kNumSemaphores, and sem_unlock().
 {
   uint16_t i;
   for (i=0; i<kNumSemaphores; ++i)
     sem_unlock(i);
   return;
 }