sxc-lib: SystemClock.h File Reference
SystemClock.h File Reference
Interface for configuring the system clock.
#include "Timer.h"
Macros
#define SYSCLOCK_OSC_DISABLE 0x0
#define SYSCLOCK_OSC_ENABLE 0x1
#define SYSCLOCK_OSC_DISABLE_TRISTATE (0x1 << 1)
#define SYSCLOCK_OSC_3RD_OVERTONE (0x1 << 2)
#define SYSCLOCK_OSC_FUNDAMENTAL 0x0
#define SYSCLOCK_HIGH_FREQ (0x1 << 3)
#define SYSCLOCK_LOW_FREQ 0x0
#define SYSCLOCK_FEEDBACK_REG_DISABLE (0x1 << 4)
#define SYSCLOCK_SELECT_HFOSC (0x1 << 10)
#define SYSCLOCK_SELECT_RC 0x0
#define SYSCLOCK_HFOSC_PLL (0x1 << 11)
#define SYSCLOCK_HFOSC_CRYSTAL 0x0
#define PLL_ENABLE 0x1
#define PLL_HF_MODE (0x1 << 13)
#define PLL_LF_MODE 0x0
#define PLL_DIVIDER_BITSHIFT 1
#define PLL_FEEDBACK_DIVIDER_BITSHIFT 7
#define SCX_BUFFER_ENABLE 0x1
#define SCX_DRIVE_STR_2mA (0x0 << 1)
#define SCX_DRIVE_STR_4mA (0x1 << 1)
#define SCX_DRIVE_STR_6mA (0x2 << 1)
#define SCX_DRIVE_STR_8mA (0x3 << 1)
#define SCX_DRIVE_STR_10mA (0x4 << 1)
#define SCX_DRIVE_STR_12mA (0x5 << 1)
#define SCX_DRIVE_STR_14mA (0x6 << 1)
#define SCX_DRIVE_STR_16mA (0x7 << 1)
#define SCX_CLK_SLEW_FAST (0x1 << 4)
#define SCX_DIVIDER_SRC_DISABLE (0x1 << 5)
#define SCX_BUF_SRC_PLL 0x0
#define SCX_BUF_SRC_RC (0x1 << 6)
#define SCX_BUF_SRC_CRYS (0x2 << 6)
#define SCX_BUF_SRC_SYSCLK (0x3 << 6)
#define SCX_BUF_CLK_DIV_SHIFT 8
#define SCX_DASI_CLK_DISABLE (0x1 << 13)
#define SCX_I2S_SRC_SYSCLK 0x0
#define SCX_I2S_SRC_RC (0x1 << 14)
#define SCX_I2S_SRC_CRYS (0x2 << 14)
#define SCX_I2S_SRC_PLL (0x3 << 14)
#define kNumSFs 7
#define kNumCFs 2
Enumerations
enum sys_freq {
_12_288_MHz = 0, _24_576_MHz = 1, _36_864_MHz = 2, _49_152_MHz = 3,
_73_728_MHz = 4, _98_304_MHz = 5, _110_592_MHz = 6
}
enum crystal_freq { crys_12_288_MHz = 0, crys_24_576_MHz = 1 }
Functions
SXC_INLINE uint16_t sys_clock_ticks_per_ms_slice (enum sys_freq sf)
Returns the number of system clock ticks per millisecond "slice" based on the provided system frequency.
SXC_INLINE uint16_t is_sysclock_src_oscn (void)
SXC_INLINE uint16_t get_pllcfg1 (enum crystal_freq cf, enum sys_freq sf)
SXC_INLINE uint16_t get_pllcfg0 (enum crystal_freq cf, enum sys_freq sf)
SXC_INLINE uint16_t get_scxaltcfg (enum crystal_freq cf)
SXC_INLINE uint16_t sys_clock_get_scu_time (void)
SXC_INLINE void sys_clock_init (enum crystal_freq cf, enum sys_freq sf)
Initiates/configures the system clock based on the given crystal resonant and desired system frequencies.
SXC_INLINE void sys_clock_wait (uint16_t duration)
Busy-waits the specified amount of time in processor 'ticks'.
Variables
const uint16_t kNumSlicesPerMs = 16
Detailed Description
Interface for configuring the system clock.
Definition in file SystemClock.h.
Macro Definition Documentation
#define kNumCFs 2
Definition at line 106 of file SystemClock.h.
#define kNumSFs 7
Definition at line 94 of file SystemClock.h.
Function Documentation
SXC_INLINE uint16_t get_pllcfg0 (enum crystal_freq cf, enum sys_freq sf)
Definition at line 159 of file SystemClock.h.
References _24_576_MHz, _36_864_MHz, _49_152_MHz, _73_728_MHz, crys_12_288_MHz, crys_24_576_MHz, PLL_DIVIDER_BITSHIFT, PLL_ENABLE, and PLL_FEEDBACK_DIVIDER_BITSHIFT.
Referenced by sys_clock_init().
 {
   switch(cf) {
   case crys_12_288_MHz:
     switch(sf) {
     case _24_576_MHz:
       return PLL_ENABLE|(0x2 << PLL_DIVIDER_BITSHIFT)|
                                          (0x8 << PLL_FEEDBACK_DIVIDER_BITSHIFT);
     case _49_152_MHz:
       return PLL_ENABLE|(0x2 << PLL_DIVIDER_BITSHIFT)|
                                         (0x10 << PLL_FEEDBACK_DIVIDER_BITSHIFT);
     case _73_728_MHz:
       return PLL_ENABLE|(0x2 << PLL_DIVIDER_BITSHIFT)|
                                         (0x18 << PLL_FEEDBACK_DIVIDER_BITSHIFT);
     default:
       return 0;
     }
   case crys_24_576_MHz:
     switch(sf) {
     case _36_864_MHz:
       return PLL_ENABLE|(0x1 << PLL_DIVIDER_BITSHIFT)|
                                          (0x3 << PLL_FEEDBACK_DIVIDER_BITSHIFT);
     case _49_152_MHz:
       return PLL_ENABLE|(0x1 << PLL_DIVIDER_BITSHIFT)|
                                          (0x2 << PLL_FEEDBACK_DIVIDER_BITSHIFT);
     case _73_728_MHz:
       return PLL_ENABLE|(0x2 << PLL_DIVIDER_BITSHIFT)|
                                          (0xC << PLL_FEEDBACK_DIVIDER_BITSHIFT);
     default:
       return 0;
     }
   }
 }
SXC_INLINE uint16_t get_pllcfg1 (enum crystal_freq cf, enum sys_freq sf)
Definition at line 154 of file SystemClock.h.
References _49_152_MHz, and crys_24_576_MHz.
Referenced by sys_clock_init().
 {
     return ((cf == crys_24_576_MHz && sf == _49_152_MHz) ? 0 : 1);
 }
SXC_INLINE uint16_t get_scxaltcfg (enum crystal_freq cf)
Definition at line 194 of file SystemClock.h.
References crys_24_576_MHz, SCX_BUF_CLK_DIV_SHIFT, SCX_BUF_SRC_CRYS, SCX_BUFFER_ENABLE, SCX_DRIVE_STR_4mA, and SCX_I2S_SRC_CRYS.
Referenced by sys_clock_init().
 {
   uint16_t alt_cfg = SCX_BUFFER_ENABLE | SCX_DRIVE_STR_4mA | SCX_BUF_SRC_CRYS |
                      SCX_I2S_SRC_CRYS;
   return (cf == crys_24_576_MHz) ? alt_cfg|(0x1 << SCX_BUF_CLK_DIV_SHIFT)
                                                                       : alt_cfg;
 }
SXC_INLINE uint16_t is_sysclock_src_oscn (void)
Definition at line 145 of file SystemClock.h.
References mock_mem_map, and SCXclkCfg.
Referenced by sys_clock_init().
 {
 #ifndef __XINC2__
   return ( (mock_mem_map[SCXclkCfg] & (0x1 << 15)) ? 1 : 0 );
 #else
   return ( (_inp(SCXclkCfg) & (0x1 << 15)) ? 1 : 0 );
 #endif
 }
SXC_INLINE uint16_t sys_clock_get_scu_time (void)
Definition at line 202 of file SystemClock.h.
References mock_mem_map, and SCUtime.
Referenced by sys_clock_wait().
 {
 #ifndef __XINC2__
   return mock_mem_map[SCUtime];
 #else
   return _inp(SCUtime);
 #endif
 }
SXC_INLINE void sys_clock_init (enum crystal_freq cf, enum sys_freq sf)
Initiates/configures the system clock based on the given crystal resonant and desired system frequencies.
Parameters
[in] cf desired crystal frequency
[in] sf desired system frequency
Definition at line 217 of file SystemClock.h.
References get_pllcfg0(), get_pllcfg1(), get_scxaltcfg(), is_sysclock_src_oscn(), SCXaltCfg, SCXclkCfg, SCXPLLCfg0, SCXPLLCfg1, SYSCLOCK_HFOSC_PLL, and SYSCLOCK_SELECT_HFOSC.
 {
 //#ifndef __XINC2__
 //#else
   _outp( _inp(SCXclkCfg)&~SYSCLOCK_SELECT_HFOSC, SCXclkCfg );
   while (is_sysclock_src_oscn())
     continue;
   _outp( get_pllcfg1(cf, sf), SCXPLLCfg1 );
   _outp( get_pllcfg0(cf, sf), SCXPLLCfg0 );
   _outp( _inp(SCXclkCfg)&~SYSCLOCK_SELECT_HFOSC, SCXclkCfg );
   while (is_sysclock_src_oscn())
     continue;
   _outp(_inp(SCXclkCfg)|SYSCLOCK_HFOSC_PLL|SYSCLOCK_SELECT_HFOSC,SCXclkCfg);
   while (!is_sysclock_src_oscn())
     continue;
   _outp(get_scxaltcfg(cf), SCXaltCfg);
 //#endif
 }
SXC_INLINE uint16_t sys_clock_ticks_per_ms_slice (enum sys_freq sf)
Returns the number of system clock ticks per millisecond "slice" based on the provided system frequency.
Parameters
[in] sf System frequency for which to eval
Returns
The number of system clock ticks per millisecond "sliace"
Definition at line 116 of file SystemClock.h.
References _110_592_MHz, _12_288_MHz, _24_576_MHz, _36_864_MHz, _49_152_MHz, _73_728_MHz, _98_304_MHz, and kNumSlicesPerMs.
 {
   uint16_t ticks;
   switch(sf) {
     case _12_288_MHz:
       ticks = 12288/kNumSlicesPerMs;
       break;
     case _24_576_MHz:
       ticks = 24576/kNumSlicesPerMs;
       break;
     case _49_152_MHz:
       ticks = 49152/kNumSlicesPerMs;
       break;
     case _36_864_MHz:
       ticks = 36864/kNumSlicesPerMs;
       break;
     case _73_728_MHz:
       ticks = 73728/kNumSlicesPerMs;
       break;
     case _98_304_MHz:
       ticks = 98304/kNumSlicesPerMs;
       break;
     case _110_592_MHz:
       ticks = 110592/kNumSlicesPerMs;
       break;
   }
   return ticks;
 }
SXC_INLINE void sys_clock_wait (uint16_t duration)
Busy-waits the specified amount of time in processor 'ticks'.
Parameters
[in] duration number of ticks to wait (ticks=seconds*sys_freq)
Definition at line 245 of file SystemClock.h.
References sys_clock_get_scu_time().
Referenced by i2c_read_byte(), i2c_write_byte(), i2c_write_start(), i2c_write_stop(), uart_read_byte(), and uart_write_byte().
 {
   uint16_t initial_time = sys_clock_get_scu_time();
   while (sys_clock_get_scu_time() - initial_time < duration)
     continue;
 }
Variable Documentation
const uint16_t kNumSlicesPerMs = 16
Definition at line 108 of file SystemClock.h.
Referenced by sys_clock_ticks_per_ms_slice().