sxc-lib: BBU.h File Reference
BBU.h File Reference
Interface for the XInC2 baseband unit.
#include "SystemClock.h"
Macros
#define BBU_ENABLE (1 << 0)
#define BBU_TX_ENABLE (1 << 1)
#define BBU_RAW_ENABLE (1 << 2)
#define BUU_FORCE_HUNT (1 << 3)
#define BBU_LOOPBACK_MODE (1 << 4)
#define BBU_USE_CLK_IN (1 << 5)
#define BBU_CLK_DETECT_ENABLE (1 << 6)
#define BBU_CLK_ENABLE (1 << 7)
#define BBU_CLK_OUT_RISING_EDGE (1 << 8)
#define BBU_CLK_IN_RISING_EDGE (1 << 9)
#define BBU_TX_MODE_RET_TO_ZERO (1 << 10)
#define BBU_RX_MODE_RET_TO_ZERO (1 << 11)
#define BBU_BIDIRECTION_ENABLE (1 << 12)
#define BBU_EXT_CLK_TO_INC (1 << 13)
#define BBU_USE_NEW_BAUD_GEN (1 << 14)
#define BBU_ROM_ENABLE (1 << 15)
#define kNumBBUs 10
#define RX_PREAMBLE_BIT (1 << 15)
Enumerations
enum BBUMode { BitStream, SlowClock }
enum BaudRate { _19200, _57600, _115200, _2048000 }
enum BBU_name { BBU0 = 0, BBU1 = 1 }
enum BBU_reg_type {
BBU_CFG0, BBU_CFG1, BBU_start, BBU_brg,
BBU_time, BBU_TX, BBU_rx4, BBU_rx6,
BBU_rx
}
Functions
SXC_INLINE uint16_t get_bbu_address (enum BBU_reg_type type, enum BBU_name name)
SXC_INLINE void bbu_setup (enum BaudRate br, enum BBUMode mode, enum BBU_name name, uint16_t start_word)
SXC_INLINE void bbu_lock_timing (enum BBU_name name)
SXC_INLINE void bbu_unlock_timing (enum BBU_name name)
SXC_INLINE uint16_t bbu_peek (enum BBU_name name)
SXC_INLINE uint16_t bbu_get_word (enum BBU_name name)
SXC_INLINE uint16_t bbu_contains_preamble (enum BBU_name name)
SXC_INLINE void bbu_push_word (uint16_t input, enum BBU_name name)
SXC_INLINE uint16_t bbu_get_time (enum BBU_name name)
Detailed Description
Interface for the XInC2 baseband unit.
Definition in file BBU.h.
Macro Definition Documentation
#define kNumBBUs 10
Definition at line 35 of file BBU.h.
Referenced by bbu_contains_preamble(), bbu_get_time(), bbu_get_word(), bbu_lock_timing(), bbu_peek(), bbu_push_word(), bbu_setup(), bbu_unlock_timing(), and get_bbu_address().
#define RX_PREAMBLE_BIT (1 << 15)
Definition at line 37 of file BBU.h.
Referenced by bbu_contains_preamble().
Enumeration Type Documentation
enum BaudRate
Enumerator
_19200
_57600
_115200
_2048000
Definition at line 44 of file BBU.h.
               {
   _19200,
   _57600,
   _115200,
   _2048000
 };
enum BBU_name
Enumerator
BBU0
BBU1
Definition at line 51 of file BBU.h.
               {
   BBU0 = 0,
   BBU1 = 1
 };
enum BBU_reg_type
Enumerator
BBU_CFG0
BBU_CFG1
BBU_start
BBU_brg
BBU_time
BBU_TX
BBU_rx4
BBU_rx6
BBU_rx
Definition at line 56 of file BBU.h.
                   {
   BBU_CFG0,
   BBU_CFG1,
   BBU_start,
   BBU_brg,
   BBU_time,
   BBU_TX,
   BBU_rx4,
   BBU_rx6,
   BBU_rx
 };
enum BBUMode
Enumerator
BitStream
SlowClock
Definition at line 39 of file BBU.h.
              {
   BitStream,
   SlowClock
 };
Function Documentation
SXC_INLINE uint16_t bbu_contains_preamble (enum BBU_name name)
Definition at line 229 of file BBU.h.
References BBU_rx4, get_bbu_address(), kNumBBUs, RX_PREAMBLE_BIT, and safe_mode_assert.
 {
   safe_mode_assert(name < kNumBBUs);
 #ifndef __XINC2__
   return 0; //dummy
 #else
   return (_inp(get_bbu_address(BBU_rx4, name)) & RX_PREAMBLE_BIT) != 0;
 #endif
 }
SXC_INLINE uint16_t bbu_get_time (enum BBU_name name)
Definition at line 249 of file BBU.h.
References BBU_time, get_bbu_address(), kNumBBUs, and safe_mode_assert.
{
   safe_mode_assert(name < kNumBBUs);
 #ifndef __XINC2__
   return 0;
 #else
   return _inp(get_bbu_address(BBU_time, name));
 #endif
 }
SXC_INLINE uint16_t bbu_get_word (enum BBU_name name)
Definition at line 217 of file BBU.h.
References BBU_rx, BBU_rx4, get_bbu_address(), kNumBBUs, and safe_mode_assert.
 {
   safe_mode_assert(name < kNumBBUs);
 #ifndef __XINC2__
   return 0; //dummy
 #else
   _inp(get_bbu_address(BBU_rx4, name)); //locks word alignment
   return _inp(get_bbu_address(BBU_rx, name));
 #endif
 }
SXC_INLINE void bbu_lock_timing (enum BBU_name name)
Definition at line 183 of file BBU.h.
References BBU_CFG0, BBU_RAW_ENABLE, get_bbu_address(), kNumBBUs, and safe_mode_assert.
 {
   safe_mode_assert(name < kNumBBUs);
 #ifndef __XINC2__
 #else
   uint16_t addr = get_bbu_address(BBU_CFG0, name);
   _outp(_inp(addr) | BBU_RAW_ENABLE, addr);
 #endif
 }
SXC_INLINE uint16_t bbu_peek (enum BBU_name name)
Definition at line 205 of file BBU.h.
References BBU_rx, get_bbu_address(), kNumBBUs, and safe_mode_assert.
 {
   safe_mode_assert(name < kNumBBUs);
 #ifndef __XINC2__
   return 0; //dummy
 #else
   return _inp(get_bbu_address(BBU_rx, name));
 #endif
 }
SXC_INLINE void bbu_push_word (uint16_t input, enum BBU_name name)
Definition at line 240 of file BBU.h.
References BBU_TX, get_bbu_address(), kNumBBUs, and safe_mode_assert.
 {
   safe_mode_assert(name < kNumBBUs);
 #ifndef __XINC2__
 #else
   _outp(input, get_bbu_address(BBU_TX, name)); //NB: blocks on word alignment
 #endif
 }
SXC_INLINE void bbu_setup (enum BaudRate br, enum BBUMode mode, enum BBU_name name, uint16_t start_word)
Definition at line 159 of file BBU.h.
References BBU_BIDIRECTION_ENABLE, BBU_brg, BBU_CFG0, BBU_ENABLE, BBU_ROM_ENABLE, BBU_start, BBU_TX_ENABLE, BitStream, get_bbu_address(), kNumBBUs, safe_mode_assert, and SlowClock.
 {
   safe_mode_assert(name < kNumBBUs);
 //#ifndef __XINC2__
 //#else
   switch(mode) {
   case BitStream:
     _outp(BBU_BIDIRECTION_ENABLE|BBU_ENABLE|BBU_ROM_ENABLE|BBU_TX_ENABLE,
       get_bbu_address(BBU_CFG0, name));
     _outp(start_word, get_bbu_address(BBU_start, name));
     _outp(br, get_bbu_address(BBU_brg, name));
     break;
   case SlowClock:
     _outp(0, get_bbu_address(BBU_CFG0, name));
     _outp(br, get_bbu_address(BBU_brg, name));
     break;
   default:
       break;
   }
 //#endif
 }
SXC_INLINE void bbu_unlock_timing (enum BBU_name name)
Definition at line 194 of file BBU.h.
References BBU_CFG0, BBU_RAW_ENABLE, get_bbu_address(), kNumBBUs, and safe_mode_assert.
 {
   safe_mode_assert(name < kNumBBUs);
 #ifndef __XINC2__
 #else
   uint16_t addr = get_bbu_address(BBU_CFG0, name);
   _outp(_inp(addr) & ~BBU_RAW_ENABLE, addr);
 #endif
 }
SXC_INLINE uint16_t get_bbu_address (enum BBU_reg_type type, enum BBU_name name)
Definition at line 108 of file BBU.h.
References BBU0, BBU0brg, BBU0cfg0, BBU0cfg1, BBU0rx, BBU0rx4, BBU0rx6, BBU0start, BBU0time, BBU0tx, BBU1, BBU1brg, BBU1cfg0, BBU1cfg1, BBU1rx, BBU1rx4, BBU1start, BBU1time, BBU1tx, BBU_brg, BBU_CFG0, BBU_CFG1, BBU_rx, BBU_rx4, BBU_rx6, BBU_start, BBU_time, BBU_TX, kNumBBUs, and safe_mode_assert.
Referenced by bbu_contains_preamble(), bbu_get_time(), bbu_get_word(), bbu_lock_timing(), bbu_peek(), bbu_push_word(), bbu_setup(), and bbu_unlock_timing().
 {
   safe_mode_assert(name < kNumBBUs);
   switch(name) {
   case BBU0:
     switch(type) {
     case BBU_CFG0:
       return BBU0cfg0;
     case BBU_CFG1:
       return BBU0cfg1;
     case BBU_start:
       return BBU0start;
     case BBU_brg:
       return BBU0brg;
     case BBU_time:
       return BBU0time;
     case BBU_TX:
       return BBU0tx;
     case BBU_rx4:
       return BBU0rx4;
     case BBU_rx6:
       return BBU0rx6;
     case BBU_rx:
       return BBU0rx;
     }
   case BBU1:
     switch(type) {
     case BBU_CFG0:
       return BBU1cfg0;
     case BBU_CFG1:
       return BBU1cfg1;
     case BBU_start:
       return BBU1start;
     case BBU_brg:
       return BBU1brg;
     case BBU_time:
       return BBU1time;
     case BBU_TX:
       return BBU1tx;
     case BBU_rx4:
       return BBU1rx4;
     case BBU_rx6:
       return 0; //BBU1 doesn't have this register
     case BBU_rx:
       return BBU1rx;
     }
   }
   return 0;
 }