sxc-lib: GPIO.h File Reference
GPIO.h File Reference
Interface for accessing the GPIO ports on the XInC2 processor. These functions are NOT thread-safe: manual semaphore management is required. See the XInC2 manual for hardware layout for a much better understanding.
#include "Semaphore.h"
Macros
#define kNumGPIOPorts 10
Enumerations
enum GPIO_port_name {
GPIO_A = 0, GPIO_B = 1, GPIO_C = 2, GPIO_D = 3,
GPIO_E = 4, GPIO_F = 5, GPIO_G = 6, GPIO_H = 7,
GPIO_I = 8, GPIO_J = 9
}
Functions
SXC_INLINE void gpio_set_config (uint16_t cfg, enum GPIO_port_name port)
Configures the selected GPIO port pins' directionality based on the provided configuration. CLOBBERS THE OUTPUT BUFFER REGISTER (LSB). Call gpio_set_config((gpio_get_config() & 0xFF) | cfg) to avoid this, if you care.
SXC_INLINE uint16_t gpio_get_config (enum GPIO_port_name port)
Returns the selected GPIO port pins' current directionality.
SXC_INLINE uint16_t gpio_read (enum GPIO_port_name port)
Reads the logical values on the pins of the selected GPIO port.
SXC_INLINE void gpio_write (uint16_t input, enum GPIO_port_name port)
Writes the individual bit values of the input to their corresponding pins in the selected GPIO port. Only pins configured to be outputs are affected. Only the lower byte of the input matters.
SXC_INLINE void gpio_atomic_pin_set (uint16_t pin_num, enum GPIO_port_name port, uint16_t sem_num)
Atomically sets the desired pin in the desired port to 1.
SXC_INLINE void gpio_atomic_pin_unset (uint16_t pin_num, enum GPIO_port_name port, uint16_t sem_num)
Atomically sets the desired pin in the desired port to 0.
Detailed Description
Interface for accessing the GPIO ports on the XInC2 processor. These functions are NOT thread-safe: manual semaphore management is required. See the XInC2 manual for hardware layout for a much better understanding.
Definition in file GPIO.h.
Macro Definition Documentation
#define kNumGPIOPorts 10
Definition at line 33 of file GPIO.h.
Referenced by gpio_get_config(), gpio_read(), gpio_set_config(), and gpio_write().
Function Documentation
SXC_INLINE void gpio_atomic_pin_set (uint16_t pin_num, enum GPIO_port_name port, uint16_t sem_num)
Atomically sets the desired pin in the desired port to 1.
Parameters
[in] pin_num The pin to set
[in] port The GPIO port to target.
[in] sem_num Semaphore to acquire for atomicity.
Definition at line 220 of file GPIO.h.
References gpio_read(), gpio_write(), sem_lock(), and sem_unlock().
 {
   sem_lock(sem_num);
   uint16_t value = gpio_read(port);
   gpio_write(value|(1 << pin_num), port);
   sem_unlock(sem_num);
 }
SXC_INLINE void gpio_atomic_pin_unset (uint16_t pin_num, enum GPIO_port_name port, uint16_t sem_num)
Atomically sets the desired pin in the desired port to 0.
Parameters
[in] pin_num The pin to set
[in] port The GPIO port to target.
[in] sem_num Semaphore to acquire for atomicity.
Definition at line 235 of file GPIO.h.
References gpio_read(), gpio_write(), sem_lock(), and sem_unlock().
 {
   sem_lock(sem_num);
   uint16_t value = gpio_read(port);
   gpio_write(value&~(1 << pin_num), port);
   sem_unlock(sem_num);
 }
SXC_INLINE uint16_t gpio_get_config (enum GPIO_port_name port)
Returns the selected GPIO port pins' current directionality.
Parameters
[in] port The selected GPIO port.
Returns
Desired pin's configuration at time of function call. Set bits correspond to output pins, and cleared bits correspond to input pins.
Definition at line 93 of file GPIO.h.
References GPAcfg, GPBcfg, GPCcfg, GPDcfg, GPEcfg, GPFcfg, GPGcfg, GPHcfg, GPIcfg, GPIO_A, GPIO_B, GPIO_C, GPIO_D, GPIO_E, GPIO_F, GPIO_G, GPIO_H, GPIO_I, GPIO_J, GPJcfg, kNumGPIOPorts, and safe_mode_assert.
Referenced by globalPin_set_dir().
 {
   safe_mode_assert(port < kNumGPIOPorts);
 #ifndef __XINC2__
 #else
   switch(port){
   case GPIO_A:
     return _inp(GPAcfg);
   case GPIO_B:
     return _inp(GPBcfg);
   case GPIO_C:
     return _inp(GPCcfg);
   case GPIO_D:
     return _inp(GPDcfg);
   case GPIO_E:
     return _inp(GPEcfg);
   case GPIO_F:
     return _inp(GPFcfg);
   case GPIO_G:
     return _inp(GPGcfg);
   case GPIO_H:
     return _inp(GPHcfg);
   case GPIO_I:
     return _inp(GPIcfg);
   case GPIO_J:
     return _inp(GPJcfg);
   default:
     break;
   }
 #endif
   return 0;
 }
SXC_INLINE uint16_t gpio_read (enum GPIO_port_name port)
Reads the logical values on the pins of the selected GPIO port.
Parameters
[in] port The GPIO port to target.
Returns
The selected GPIO port's pins' logical values. Returns 0 for an invalid GPIO.
Definition at line 132 of file GPIO.h.
References GPAin, GPBin, GPCin, GPDin, GPEin, GPFin, GPGin, GPHin, GPIin, GPIO_A, GPIO_B, GPIO_C, GPIO_D, GPIO_E, GPIO_F, GPIO_G, GPIO_H, GPIO_I, GPIO_J, GPJin, kNumGPIOPorts, and safe_mode_assert.
Referenced by globalPin_read(), globalPin_read_raw(), globalPin_write(), globalPin_write_raw(), gpio_atomic_pin_set(), and gpio_atomic_pin_unset().
 {
   safe_mode_assert(port < kNumGPIOPorts);
 #ifndef __XINC2__
 #else
   switch(port){
   case GPIO_A:
     return _inp(GPAin);
   case GPIO_B:
     return _inp(GPBin);
   case GPIO_C:
     return _inp(GPCin);
   case GPIO_D:
     return _inp(GPDin);
   case GPIO_E:
     return _inp(GPEin);
   case GPIO_F:
     return _inp(GPFin);
   case GPIO_G:
     return _inp(GPGin);
   case GPIO_H:
     return _inp(GPHin);
   case GPIO_I:
     return _inp(GPIin);
   case GPIO_J:
     return _inp(GPJin);
   default:
     break;
   }
 #endif
   return 0;
 }
SXC_INLINE void gpio_set_config (uint16_t cfg, enum GPIO_port_name port)
Configures the selected GPIO port pins' directionality based on the provided configuration. CLOBBERS THE OUTPUT BUFFER REGISTER (LSB). Call gpio_set_config((gpio_get_config() & 0xFF) | cfg) to avoid this, if you care.
Parameters
[in] cfg Desired pin configuration. Lower byte clobbers output buffer register. Set bits in the upper byte cause that pin to be an output; cleared bits correlate to input pins. Because this is the MSB, bit8 of the entire word corresponds to pin0, bit9 to pin1, and so on.
[in] port The selected GPIO port.
Definition at line 45 of file GPIO.h.
References GPAcfg, GPBcfg, GPCcfg, GPDcfg, GPEcfg, GPFcfg, GPGcfg, GPHcfg, GPIcfg, GPIO_A, GPIO_B, GPIO_C, GPIO_D, GPIO_E, GPIO_F, GPIO_G, GPIO_H, GPIO_I, GPIO_J, GPJcfg, kNumGPIOPorts, and safe_mode_assert.
Referenced by globalPin_set_dir().
 {
   safe_mode_assert(port < kNumGPIOPorts);
 #ifndef __XINC2__
 #else
   switch(port){
   case GPIO_A:
     _outp(cfg, GPAcfg);
     break;
   case GPIO_B:
     _outp(cfg, GPBcfg);
     break;
   case GPIO_C:
     _outp(cfg, GPCcfg);
     break;
   case GPIO_D:
     _outp(cfg, GPDcfg);
     break;
   case GPIO_E:
     _outp(cfg, GPEcfg);
     break;
   case GPIO_F:
     _outp(cfg, GPFcfg);
     break;
   case GPIO_G:
     _outp(cfg, GPGcfg);
     break;
   case GPIO_H:
     _outp(cfg, GPHcfg);
     break;
   case GPIO_I:
     _outp(cfg, GPIcfg);
     break;
   case GPIO_J:
     _outp(cfg, GPJcfg);
     break;
   default:
     break;
   }
 #endif
 }
SXC_INLINE void gpio_write (uint16_t input, enum GPIO_port_name port)
Writes the individual bit values of the input to their corresponding pins in the selected GPIO port. Only pins configured to be outputs are affected. Only the lower byte of the input matters.
Parameters
[in] input Lower byte: Bit values to write to corresponding pins.
[in] port The GPIO port to target.
Definition at line 172 of file GPIO.h.
References GPAout, GPBout, GPCout, GPDout, GPEout, GPFout, GPGout, GPHout, GPIO_A, GPIO_B, GPIO_C, GPIO_D, GPIO_E, GPIO_F, GPIO_G, GPIO_H, GPIO_I, GPIO_J, GPIout, GPJout, kNumGPIOPorts, and safe_mode_assert.
Referenced by globalPin_write(), globalPin_write_raw(), gpio_atomic_pin_set(), and gpio_atomic_pin_unset().
 {
   safe_mode_assert(port < kNumGPIOPorts);
 #ifndef __XINC2__
 #else
   switch(port){
   case GPIO_A:
     _outp(input, GPAout);
     break;
   case GPIO_B:
     _outp(input, GPBout);
     break;
   case GPIO_C:
     _outp(input, GPCout);
     break;
   case GPIO_D:
     _outp(input, GPDout);
     break;
   case GPIO_E:
     _outp(input, GPEout);
     break;
   case GPIO_F:
     _outp(input, GPFout);
     break;
   case GPIO_G:
     _outp(input, GPGout);
     break;
   case GPIO_H:
     _outp(input, GPHout);
     break;
   case GPIO_I:
     _outp(input, GPIout);
     break;
   case GPIO_J:
     _outp(input, GPJout);
     break;
   default:
     break;
   }
 #endif
 }