sxc-lib: I2C.h File Reference
I2C.h File Reference
Convenience functions and implementation using 2 arbitrary GPIO pins in order to utilize the I2C protocol.
#include "SXC.h"
#include "GPIO.h"
#include "SystemClock.h"
#include "Structs.h"
Data Structures
struct I2C_Pin_Pair
Typedefs
typedef struct I2C_Pin_Pair I2C_Pin_Pair
Enumerations
enum I2C_Mode { I2C_Master, I2C_Slave }
Functions
SXC_INLINE void i2c_set_mode (enum I2C_Mode mode, I2C_Pin_Pair const *pins)
Sets the desired I2C_Pin_Pair (corresponding to the current device) as either an I2C master or slave.
SXC_INLINE void i2c_write_start (I2C_Pin_Pair const *pins)
Writes the START sequence onto the I2C line.
SXC_INLINE void i2c_write_stop (I2C_Pin_Pair const *pins)
Writes the STOP sequence onto the I2C line.
SXC_INLINE uint16_t i2c_write_byte (uint16_t byte, I2C_Pin_Pair const *pins)
Writes an 8-bit byte (the LSB of byte) onto the I2C line. Returns 1 if an ACK is read on the line after writing, returns 0 else. May only be called if the device is set as an I2C master; otherwise, undefined behaviour occurs.
SXC_INLINE uint16_t i2c_read_byte (uint16_t nack, I2C_Pin_Pair const *pins)
Reads an 8-bit byte from the I2C line. May only be called if the device is set as an I2C master; else, undefined behaviour occurs.
SXC_INLINE uint16_t i2c_write_to_addr (uint16_t dest_addr, uint16_t byte, I2C_Pin_Pair const *pins)
Writes an 8-bit byte (the LSB of byte) to the device with the specified address. Returns 1 if the operation succeeds and is ACKed at all stages; 0 else. Function may only be called if the device is set as an I2C master; otherwise, undefined behaviour occurs.
SXC_INLINE uint16_t i2c_write_to_register (uint16_t dest_addr, uint16_t dest_reg, uint16_t byte, I2C_Pin_Pair const *pins)
Writes an 8-bit byte (the LSB of byte) to the register of the device with the specified addresses. Returns 1 if the operation succeeds and is ACKed at all stages; 0 else. Function may only be called if the device is set as an I2C master; otherwise, undefined behaviour occurs.
SXC_INLINE uint16_t i2c_write_buf_to_register (uint16_t dest_addr, uint16_t dest_reg, uint16_t *buf, size_t len, I2C_Pin_Pair const *pins)
Writes an array of 8-bit bytes (the LSBs of the array elements) to the register of the device with the specified addresses. No array bound checks are done. Returns 1 if the operation succeeds and is ACKed at all stages; 0 else. Function may only be called if the device is set as an I2C master; otherwise, undefined behaviour occurs.
Detailed Description
Convenience functions and implementation using 2 arbitrary GPIO pins in order to utilize the I2C protocol.
Definition in file I2C.h.
Typedef Documentation
typedef struct I2C_Pin_Pair I2C_Pin_Pair
Enumeration Type Documentation
enum I2C_Mode
Enumerator
I2C_Master
I2C_Slave
Definition at line 17 of file I2C.h.
               {
   I2C_Master,
   I2C_Slave
 };
Function Documentation
SXC_INLINE uint16_t i2c_read_byte (uint16_t nack, I2C_Pin_Pair const * pins)
Reads an 8-bit byte from the I2C line. May only be called if the device is set as an I2C master; else, undefined behaviour occurs.
Parameters
[in] nack If non-zero, respond with a "NACK" on the line after reading.
[in] pins Pointer to the I2C_Pin_Pair of interest
Returns
The 8-bit byte in the LSB of a 16-bit word
Definition at line 135 of file I2C.h.
References globalPin_read_raw(), globalPin_set_dir(), globalPin_write_raw(), PinDir_Input, PinDir_Output, I2C_Pin_Pair::scl, I2C_Pin_Pair::sda, sys_clock_wait(), and I2C_Pin_Pair::timeout.
 {
   uint16_t byte = 0;
   for (int16_t i = 7; i >= 0; i--) {
     globalPin_set_dir(PinDir_Input, &pins->scl);
     while(!globalPin_read_raw(&pins->scl));
     sys_clock_wait(pins->timeout);
     byte += byte + globalPin_read_raw(&pins->sda);
     globalPin_set_dir(PinDir_Output, &pins->scl);
     globalPin_write_raw(0, &pins->scl);
     sys_clock_wait(pins->timeout);
   }
   if (nack) {
     globalPin_set_dir(PinDir_Input, &pins->sda);
   }
   else {
     globalPin_set_dir(PinDir_Output, &pins->sda);
     globalPin_write_raw(0, &pins->sda);
   }
   sys_clock_wait(pins->timeout);
   globalPin_set_dir(PinDir_Input, &pins->scl);
   sys_clock_wait(pins->timeout);
   while(!globalPin_read_raw(&pins->scl));
   sys_clock_wait(pins->timeout);
   globalPin_set_dir(PinDir_Output, &pins->scl);
   globalPin_write_raw(0, &pins->scl);
   sys_clock_wait(pins->timeout);
   globalPin_set_dir(PinDir_Input, &pins->sda);
   return byte;
 }
SXC_INLINE void i2c_set_mode (enum I2C_Mode mode, I2C_Pin_Pair const * pins)
Sets the desired I2C_Pin_Pair (corresponding to the current device) as either an I2C master or slave.
Parameters
[in] mode Selects whether the device is to be a slave or a master
[in] pins Pointer to the I2C_Pin_Pair of interest
Definition at line 36 of file I2C.h.
References globalPin_set_dir(), I2C_Master, I2C_Slave, PinDir_Input, PinDir_Output, I2C_Pin_Pair::scl, and I2C_Pin_Pair::sda.
 {
   switch(mode) {
   case I2C_Master:
     globalPin_set_dir(PinDir_Output, &pins->scl);
     break;
   case I2C_Slave:
     globalPin_set_dir(PinDir_Input, &pins->scl);
     break;
   }
   globalPin_set_dir(PinDir_Input, &pins->sda);
 }
SXC_INLINE uint16_t i2c_write_buf_to_register (uint16_t dest_addr, uint16_t dest_reg, uint16_t * buf, size_t len, I2C_Pin_Pair const * pins)
Writes an array of 8-bit bytes (the LSBs of the array elements) to the register of the device with the specified addresses. No array bound checks are done. Returns 1 if the operation succeeds and is ACKed at all stages; 0 else. Function may only be called if the device is set as an I2C master; otherwise, undefined behaviour occurs.
Parameters
[in] dest_addr 16-bit word whose LSB is the I2C address to write to.
[in] dest_reg 16-bit word whose LSB is the address of the register to write to.
[in] buf Array of 16-bit words whose LSBs are written. MSBs are ignored.
[in] len Length of the array (number of bytes to write)
[in] pins Pointer to the I2C_Pin_Pair of interest
Returns
1 if all expected ACKs are read on the line after writing, 0 else
Definition at line 241 of file I2C.h.
References i2c_write_byte(), i2c_write_start(), and i2c_write_stop().
 {
   i2c_write_start(pins);
     if (!i2c_write_byte(dest_addr, pins))
       return 0;
     if (!i2c_write_byte(dest_reg, pins))
       return 0;
     for (size_t i = 0; i < len ; i++) {
       if (!i2c_write_byte(buf[i], pins))
         return 0;
     }
   i2c_write_stop(pins);
   return 1;
 }
SXC_INLINE uint16_t i2c_write_byte (uint16_t byte, I2C_Pin_Pair const * pins)
Writes an 8-bit byte (the LSB of byte) onto the I2C line. Returns 1 if an ACK is read on the line after writing, returns 0 else. May only be called if the device is set as an I2C master; otherwise, undefined behaviour occurs.
Parameters
[in] byte 16-bit word whose LSB is written onto the I2C line. MSB is ignored.
[in] pins Pointer to the I2C_Pin_Pair of interest
Returns
1 if an ACK is read on the line after writing, 0 else
Definition at line 93 of file I2C.h.
References globalPin_read_raw(), globalPin_set_dir(), globalPin_write_raw(), PinDir_Input, PinDir_Output, I2C_Pin_Pair::scl, I2C_Pin_Pair::sda, sys_clock_wait(), and I2C_Pin_Pair::timeout.
Referenced by i2c_write_buf_to_register(), i2c_write_to_addr(), and i2c_write_to_register().
 {
   for (int16_t i = 7; i >= 0; --i) {
     if(_rol(1, i) & byte) {
       globalPin_set_dir(PinDir_Input, &pins->sda);
     }
     else {
       globalPin_set_dir(PinDir_Output, &pins->sda);
       globalPin_write_raw(0, &pins->sda);
     }
     sys_clock_wait(pins->timeout);
     globalPin_set_dir(PinDir_Input, &pins->scl);
     sys_clock_wait(pins->timeout);
     sys_clock_wait(pins->timeout);
     globalPin_set_dir(PinDir_Output, &pins->scl);
     globalPin_write_raw(0, &pins->scl);
   }
   globalPin_set_dir(PinDir_Input, &pins->sda);
   sys_clock_wait(pins->timeout);
   globalPin_set_dir(PinDir_Input, &pins->scl);
   sys_clock_wait(pins->timeout);
   while(!globalPin_read_raw(&pins->scl));
   uint16_t retVal = !globalPin_read_raw(&pins->sda);
   sys_clock_wait(pins->timeout);
   globalPin_set_dir(PinDir_Output, &pins->scl);
   globalPin_write_raw(0, &pins->scl);
   sys_clock_wait(pins->timeout);
   return retVal;
 }
SXC_INLINE void i2c_write_start (I2C_Pin_Pair const * pins)
Writes the START sequence onto the I2C line.
Parameters
[in] pins Pointer to the I2C_Pin_Pair of interest
Definition at line 54 of file I2C.h.
References globalPin_read_raw(), globalPin_set_dir(), globalPin_write_raw(), PinDir_Input, PinDir_Output, I2C_Pin_Pair::scl, I2C_Pin_Pair::sda, sys_clock_wait(), and I2C_Pin_Pair::timeout.
Referenced by i2c_write_buf_to_register(), i2c_write_to_addr(), and i2c_write_to_register().
 {
   while(!globalPin_read_raw(&pins->scl));
   globalPin_set_dir(PinDir_Output, &pins->sda);
   globalPin_write_raw(0, &pins->sda);
   sys_clock_wait(pins->timeout);
   sys_clock_wait(pins->timeout);
   globalPin_set_dir(PinDir_Output, &pins->scl);
   globalPin_write_raw(0, &pins->scl);
   sys_clock_wait(pins->timeout);
   globalPin_set_dir(PinDir_Input, &pins->sda);
 }
SXC_INLINE void i2c_write_stop (I2C_Pin_Pair const * pins)
Writes the STOP sequence onto the I2C line.
Parameters
[in] pins Pointer to the I2C_Pin_Pair of interest
Definition at line 71 of file I2C.h.
References globalPin_set_dir(), globalPin_write_raw(), PinDir_Input, PinDir_Output, I2C_Pin_Pair::scl, I2C_Pin_Pair::sda, sys_clock_wait(), and I2C_Pin_Pair::timeout.
Referenced by i2c_write_buf_to_register(), i2c_write_to_addr(), and i2c_write_to_register().
 {
   globalPin_set_dir(PinDir_Output, &pins->sda);
   globalPin_set_dir(PinDir_Output, &pins->scl);
   globalPin_write_raw(0, &pins->sda);
   globalPin_write_raw(0, &pins->scl);
   sys_clock_wait(pins->timeout);
   globalPin_set_dir(PinDir_Input, &pins->scl);
   sys_clock_wait(pins->timeout);
   sys_clock_wait(pins->timeout);
   globalPin_set_dir(PinDir_Input, &pins->sda);
 }
SXC_INLINE uint16_t i2c_write_to_addr (uint16_t dest_addr, uint16_t byte, I2C_Pin_Pair const * pins)
Writes an 8-bit byte (the LSB of byte) to the device with the specified address. Returns 1 if the operation succeeds and is ACKed at all stages; 0 else. Function may only be called if the device is set as an I2C master; otherwise, undefined behaviour occurs.
Parameters
[in] dest_addr 16-bit word whose LSB is the I2C address to write to.
[in] byte 16-bit word whose LSB is written. MSB is ignored.
[in] pins Pointer to the I2C_Pin_Pair of interest
Returns
1 if all expected ACKs are read on the line after writing, 0 else
Definition at line 181 of file I2C.h.
References i2c_write_byte(), i2c_write_start(), and i2c_write_stop().
 {
   i2c_write_start(pins);
   if (!i2c_write_byte(dest_addr, pins))
     return 0;
   if (!i2c_write_byte(byte, pins))
     return 0;
   i2c_write_stop(pins);
   return 1;
 }
SXC_INLINE uint16_t i2c_write_to_register (uint16_t dest_addr, uint16_t dest_reg, uint16_t byte, I2C_Pin_Pair const * pins)
Writes an 8-bit byte (the LSB of byte) to the register of the device with the specified addresses. Returns 1 if the operation succeeds and is ACKed at all stages; 0 else. Function may only be called if the device is set as an I2C master; otherwise, undefined behaviour occurs.
Parameters
[in] dest_addr 16-bit word whose LSB is the I2C address to write to.
[in] dest_reg 16-bit word whose LSB is the address of the register to write to.
[in] byte 16-bit word whose LSB is written. MSB is ignored.
[in] pins Pointer to the I2C_Pin_Pair of interest
Returns
1 if all expected ACKs are read on the line after writing, 0 else
Definition at line 209 of file I2C.h.
References i2c_write_byte(), i2c_write_start(), and i2c_write_stop().
 {
   i2c_write_start(pins);
     if (!i2c_write_byte(dest_addr, pins))
       return 0;
     if (!i2c_write_byte(dest_reg, pins))
       return 0;
     if (!i2c_write_byte(byte, pins))
       return 0;
   i2c_write_stop(pins);
   return 1;
 }