sxc-lib: SPI.h File Reference
SPI.h File Reference
Interface for configuring and reading/writing data on the serial peripheral interface.
#include "SystemClock.h"
Macros
#define kNumSPIs 2
#define SPI_ENABLE (0x1 << 0)
#define SPI_MASTER (0x1 << 1)
#define SPI_CLK_RATE_DIV_2 (0x0 << 2)
#define SPI_CLK_RATE_DIV_4 (0x1 << 2)
#define SPI_CLK_RATE_DIV_8 (0x2 << 2)
#define SPI_CLK_RATE_DIV_16 (0x3 << 2)
#define SPI_CLK_RATE_DIV_32 (0x4 << 2)
#define SPI_CLK_RATE_DIV_64 (0x5 << 2)
#define SPI_CLK_RATE_DIV_128 (0x6 << 2)
#define SPI_CLK_RATE_DIV_256 (0x7 << 2)
#define SPI_CLK_PHASE (0x1 << 5)
#define SPI_CLK_IDLE_AT_1 (0x1 << 6)
#define SPI_TX_PIN_DISABLE (0x1 << 7)
#define SPI_SLAVE_SELECT_BIT (0x1 << 15)
Enumerations
enum SPI_name { SPI0 = 0, SPI1 = 1 }
enum SPI_reg_type { SPI_CFG, SPI_TX, SPI_RX }
Functions
SXC_INLINE uint16_t get_SPI_std_cfg (enum sys_freq sf, enum SPI_name name)
Returns the standard SPI configuration value for the given system frequency and SPI.
SXC_INLINE uint16_t get_spi_addr (enum SPI_reg_type type, enum SPI_name name)
SXC_INLINE void SPI_set_config (uint16_t cfg, enum SPI_name name)
Configures the selected SPI based on the provided configuration. It is recommended to instead call SPI_set_config_optimal(), unless you know what you are doing.
SXC_INLINE uint16_t SPI_get_config (enum SPI_name name)
Returns the selected SPI's current configuration.
SXC_INLINE void SPI_set_config_optimal (enum sys_freq sf, enum SPI_name name)
Configures the selected SPI with the appropriate "best" standard configuration for the given system frequency and SPI.
SXC_INLINE void SPI_write (uint16_t val, enum SPI_name name)
Writes an 8-bit byte onto the MOSI or MISO line of the selected SPI, depending on whether the SPI is configured as a master or slave, respectively.
SXC_INLINE uint16_t SPI_read (enum SPI_name name)
Reads an 8-bit byte from the MOSI or MISO line of the selected SPI, depending on whether the SPI is configured as a slave or master, respectively.
Detailed Description
Interface for configuring and reading/writing data on the serial peripheral interface.
Definition in file SPI.h.
Macro Definition Documentation
#define kNumSPIs 2
Definition at line 24 of file SPI.h.
Referenced by get_spi_addr(), and get_SPI_std_cfg().
Enumeration Type Documentation
enum SPI_name
Enumerator
SPI0
SPI1
Definition at line 13 of file SPI.h.
               {
   SPI0 = 0,
   SPI1 = 1
 };
enum SPI_reg_type
Enumerator
SPI_CFG
SPI_TX
SPI_RX
Definition at line 18 of file SPI.h.
                   {
   SPI_CFG,
   SPI_TX,
   SPI_RX
 };
Function Documentation
SXC_INLINE uint16_t get_spi_addr (enum SPI_reg_type type, enum SPI_name name)
Definition at line 99 of file SPI.h.
References kNumSPIs, safe_mode_assert, SPI0, SPI0cfg, SPI0rx, SPI0tx, SPI1, SPI1cfg, SPI1rx, SPI1tx, SPI_CFG, SPI_RX, and SPI_TX.
Referenced by SPI_get_config(), SPI_read(), SPI_set_config(), and SPI_write().
 {
   safe_mode_assert(name < kNumSPIs);
   switch(name) {
   case SPI0:
     switch(type) {
     case SPI_CFG:
       return SPI0cfg;
     case SPI_TX:
       return SPI0tx;
     case SPI_RX:
       return SPI0rx;
     }
   case SPI1:
     switch(type) {
     case SPI_CFG:
       return SPI1cfg;
     case SPI_TX:
       return SPI1tx;
     case SPI_RX:
       return SPI1rx;
     }
   }
   return 0;
 }
SXC_INLINE uint16_t get_SPI_std_cfg (enum sys_freq sf, enum SPI_name name)
Returns the standard SPI configuration value for the given system frequency and SPI.
Parameters
[in] sf input system frequency
[in] name SPI to target
Returns
The SPI config for valid frequencies. 0 else.
Definition at line 57 of file SPI.h.
References _110_592_MHz, _12_288_MHz, _24_576_MHz, _36_864_MHz, _49_152_MHz, _73_728_MHz, _98_304_MHz, kNumSPIs, safe_mode_assert, SPI0, SPI1, SPI_CLK_RATE_DIV_128, SPI_CLK_RATE_DIV_16, SPI_CLK_RATE_DIV_2, SPI_CLK_RATE_DIV_256, SPI_CLK_RATE_DIV_32, SPI_CLK_RATE_DIV_4, SPI_CLK_RATE_DIV_64, SPI_CLK_RATE_DIV_8, SPI_ENABLE, and SPI_MASTER.
Referenced by SPI_set_config_optimal().
 {
   safe_mode_assert(name < kNumSPIs);
   switch(name) {
   case SPI0:
     switch(sf) {
     case _12_288_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_16;
     case _24_576_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_32;
     case _36_864_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_64;
     case _49_152_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_64;
     case _73_728_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_128;
     case _98_304_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_128;
     case _110_592_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_256;
     }
   case SPI1:
     switch(sf) {
     case _12_288_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_2;
     case _24_576_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_4;
     case _36_864_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_4;
     case _49_152_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_8;
     case _73_728_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_8;
     case _98_304_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_16;
     case _110_592_MHz:
       return SPI_ENABLE|SPI_MASTER|SPI_CLK_RATE_DIV_16;
     }
   }
   return 0;
 }
SXC_INLINE uint16_t SPI_get_config (enum SPI_name name)
Returns the selected SPI's current configuration.
Parameters
[in] name The selected SPI.
Returns
Desired SPI's configuration at time of function call.
Definition at line 147 of file SPI.h.
References get_spi_addr(), mock_mem_map, and SPI_CFG.
 {
   uint16_t reg = get_spi_addr(SPI_CFG, name);
 #ifndef __XINC2__
   return mock_mem_map[reg];
 #else
   return _inp(reg);
 #endif
 }
SXC_INLINE uint16_t SPI_read (enum SPI_name name)
Reads an 8-bit byte from the MOSI or MISO line of the selected SPI, depending on whether the SPI is configured as a slave or master, respectively.
Parameters
[in] name The selected SPI.
Returns
LSB: The 8-bit value on the line at the time of function call. MSB: undefined
Definition at line 193 of file SPI.h.
References get_spi_addr(), SPI_RX, and SPI_TX.
Referenced by EEPROM_read_byte(), EEPROM_read_word(), EEPROM_write_byte(), and EEPROM_write_word().
 {
 #ifndef __XINC2__
   return 0; //dummy
 #else
   uint16_t in_reg = get_spi_addr(SPI_RX, name);
   uint16_t out_reg = get_spi_addr(SPI_TX, name);
   _outp(0, out_reg); //dummy write with 0 so an accidental command isn't sent
   return _inp(in_reg);
 #endif
 }
SXC_INLINE void SPI_set_config (uint16_t cfg, enum SPI_name name)
Configures the selected SPI based on the provided configuration. It is recommended to instead call SPI_set_config_optimal(), unless you know what you are doing.
Parameters
[in] cfg Desired SPI configuration.
[in] name The selected SPI.
Definition at line 132 of file SPI.h.
References get_spi_addr(), mock_mem_map, and SPI_CFG.
Referenced by SPI_set_config_optimal().
 {
   uint16_t reg = get_spi_addr(SPI_CFG, name);
 #ifndef __XINC2__
   mock_mem_map[reg] = cfg;
 #else
   _outp(cfg, reg);
 #endif
 }
SXC_INLINE void SPI_set_config_optimal (enum sys_freq sf, enum SPI_name name)
Configures the selected SPI with the appropriate "best" standard configuration for the given system frequency and SPI.
Parameters
[in] sf The system clock frequency.
[in] name The selected SPI.
Definition at line 164 of file SPI.h.
References get_SPI_std_cfg(), and SPI_set_config().
 {
   SPI_set_config(get_SPI_std_cfg(sf, name), name);
 }
SXC_INLINE void SPI_write (uint16_t val, enum SPI_name name)
Writes an 8-bit byte onto the MOSI or MISO line of the selected SPI, depending on whether the SPI is configured as a master or slave, respectively.
Parameters
[in] val LSB: The 8-bit value to write onto the line. MSB: ignored
[in] name The selected SPI.
Definition at line 175 of file SPI.h.
References get_spi_addr(), SPI_RX, and SPI_TX.
Referenced by EEPROM_read_byte(), EEPROM_read_word(), EEPROM_write_byte(), and EEPROM_write_word().
 {
 #ifndef __XINC2__
 #else
   uint16_t out_reg = get_spi_addr(SPI_TX, name);
   uint16_t in_reg = get_spi_addr(SPI_RX, name);
   _outp(val, out_reg);
   _inp(in_reg);
 #endif
 }