sxc-lib: Structs.h File Reference
Structs.h File Reference
Logical combinations of hardware constructs for ease of implementing more complex protocols and logic.
#include "IOConfig.h"
#include "GPIO.h"
Data Structures
struct GlobalPin
Typedefs
typedef struct GlobalPin GlobalPin
Enumerations
enum PinLogicState { ON = 1, OFF = 0 }
enum GlobalPin_dir { PinDir_Input, PinDir_Output }
enum Pin_Polarity { Polar_ActiveHigh = 1, Polar_ActiveLow = 0 }
Functions
SXC_INLINE void globalPin_set_dir (enum GlobalPin_dir dir, GlobalPin const *glo_pin)
Sets the directionality of the pin encapsulated by the GlobalPin to be either output or input.
SXC_INLINE enum PinLogicState globalPin_read (GlobalPin const *glo_pin)
Returns ON (1) if the pin encapsulated by glo_pin is logically high, else returns OFF (0). Logically high refers to electrically high if the pin is active-high, else refers to electrically low if the pin is active-low. Behaviour is UNDEFINED if the pin is configured to be an output.
SXC_INLINE uint16_t globalPin_read_raw (GlobalPin const *glo_pin)
Returns 1 if the pin encapsulated by glo_pin is electrically high, else returns 0. Behaviour is UNDEFINED if the pin is configured to be an output.
SXC_INLINE void globalPin_write (enum PinLogicState input, GlobalPin const *glo_pin)
Sets or clears the pin encapsulated by glo_pin. Pin is set logically high if input is non-zero (ON); if input is zero (OFF), pin is set logically low. Logically low/high correlate to electrically low/high only if the pin is ActiveHigh; else, they correlate to the opposite. Undefined behaviour occurs if the pin is configured to be an input.
SXC_INLINE void globalPin_write_raw (uint16_t input, GlobalPin const *glo_pin)
Sets or clears the pin encapsulated by glo_pin. Pin is set electrically high if input is non-zero; if input is zero, pin is set electrically low. Undefined behaviour occurs if the pin is configured to be an input.
Detailed Description
Logical combinations of hardware constructs for ease of implementing more complex protocols and logic.
Definition in file Structs.h.
Typedef Documentation
typedef struct GlobalPin GlobalPin
Enumeration Type Documentation
enum GlobalPin_dir
Enumerator
PinDir_Input
PinDir_Output
Definition at line 20 of file Structs.h.
                    {
   PinDir_Input,
   PinDir_Output
 };
enum Pin_Polarity
Enumerator
Polar_ActiveHigh
Polar_ActiveLow
Definition at line 25 of file Structs.h.
                   {
   Polar_ActiveHigh = 1,
   Polar_ActiveLow = 0
 };
enum PinLogicState
Enumerator
ON
OFF
Definition at line 15 of file Structs.h.
                    {
   ON = 1,
   OFF = 0
 };
Function Documentation
SXC_INLINE enum PinLogicState globalPin_read (GlobalPin const * glo_pin)
Returns ON (1) if the pin encapsulated by glo_pin is logically high, else returns OFF (0). Logically high refers to electrically high if the pin is active-high, else refers to electrically low if the pin is active-low. Behaviour is UNDEFINED if the pin is configured to be an output.
Parameters
[in] glo_pin Pointer to GlobalPin struct
Returns
ON (1) if input pin is logic-high, 0 else; garbage value if pin is an output
Definition at line 66 of file Structs.h.
References gpio_read(), GlobalPin::pin, GlobalPin::polar, Polar_ActiveHigh, and GlobalPin::port.
 {
   if (glo_pin->polar == Polar_ActiveHigh)
     return (gpio_read(glo_pin->port) & glo_pin->pin) != 0;
   else
     return (gpio_read(glo_pin->port) & glo_pin->pin) == 0;
 }
SXC_INLINE uint16_t globalPin_read_raw (GlobalPin const * glo_pin)
Returns 1 if the pin encapsulated by glo_pin is electrically high, else returns 0. Behaviour is UNDEFINED if the pin is configured to be an output.
Parameters
[in] glo_pin Pointer to GlobalPin struct
Returns
1 if input pin is electrically-high, 0 else; garbage value if pin is an output
Definition at line 82 of file Structs.h.
References gpio_read(), GlobalPin::pin, and GlobalPin::port.
Referenced by i2c_read_byte(), i2c_write_byte(), i2c_write_start(), and uart_read_byte().
 {
   return (gpio_read(glo_pin->port) & glo_pin->pin) != 0;
 }
SXC_INLINE void globalPin_set_dir (enum GlobalPin_dir dir, GlobalPin const * glo_pin)
Sets the directionality of the pin encapsulated by the GlobalPin to be either output or input.
Parameters
[in] glo_pin Pointer to a GlobalPin struct
[in] dir Desired pin directionality
Definition at line 43 of file Structs.h.
References gpio_get_config(), gpio_set_config(), GlobalPin::pin, PinDir_Input, PinDir_Output, and GlobalPin::port.
Referenced by i2c_read_byte(), i2c_set_mode(), i2c_write_byte(), i2c_write_start(), and i2c_write_stop().
 {
   uint16_t curr_conf = gpio_get_config(glo_pin->port);
   switch(dir) {
   case PinDir_Input:
     gpio_set_config(curr_conf & ~(glo_pin->pin << 8), glo_pin->port);
     break;
   case PinDir_Output:
     gpio_set_config(curr_conf | (glo_pin->pin << 8), glo_pin->port);
     break;
   }
 }
SXC_INLINE void globalPin_write (enum PinLogicState input, GlobalPin const * glo_pin)
Sets or clears the pin encapsulated by glo_pin. Pin is set logically high if input is non-zero (ON); if input is zero (OFF), pin is set logically low. Logically low/high correlate to electrically low/high only if the pin is ActiveHigh; else, they correlate to the opposite. Undefined behaviour occurs if the pin is configured to be an input.
Parameters
[in] input If non-zero, pin is set high; else, pin is set low.
[in] glo_pin Pointer to GlobalPin struct
Definition at line 96 of file Structs.h.
References gpio_read(), gpio_write(), GlobalPin::pin, GlobalPin::polar, Polar_ActiveHigh, Polar_ActiveLow, and GlobalPin::port.
Referenced by EEPROM_read_byte(), EEPROM_read_word(), EEPROM_write_byte(), and EEPROM_write_word().
 {
   uint16_t or_pins = (input && glo_pin->polar == Polar_ActiveHigh) ||
     (!input && glo_pin->polar == Polar_ActiveLow);
   if (or_pins)
     gpio_write(gpio_read(glo_pin->port) | glo_pin->pin, glo_pin->port);
   else
     gpio_write(gpio_read(glo_pin->port) & ~glo_pin->pin, glo_pin->port);
 }
SXC_INLINE void globalPin_write_raw (uint16_t input, GlobalPin const * glo_pin)
Sets or clears the pin encapsulated by glo_pin. Pin is set electrically high if input is non-zero; if input is zero, pin is set electrically low. Undefined behaviour occurs if the pin is configured to be an input.
Parameters
[in] input If non-zero, pin is set high; else, pin is set low.
[in] glo_pin Pointer to GlobalPin struct
Definition at line 115 of file Structs.h.
References gpio_read(), gpio_write(), GlobalPin::pin, and GlobalPin::port.
Referenced by i2c_read_byte(), i2c_write_byte(), i2c_write_start(), i2c_write_stop(), and uart_write_byte().
 {
   if (input)
     gpio_write(gpio_read(glo_pin->port) | glo_pin->pin, glo_pin->port);
   else
     gpio_write(gpio_read(glo_pin->port) & ~glo_pin->pin, glo_pin->port);
 }