sxc-lib: Thread.h File Reference
Thread.h File Reference
Provides a convenient interface for enabling multithreading on the XInC2. Thread-safe, but all threads are equal peers and may terminate each other's execution. Uses POSIX under-the-hood for other platforms: same interface as XInC2.
#include "Semaphore.h"
#include "SFU.h"
#include <pthread.h>
Macros
#define kNumThrds 8
#define _DEFAULT_STACK_SIZE 256
#define _THREAD0_STACK_SIZE _DEFAULT_STACK_SIZE
#define _THREAD1_STACK_SIZE _DEFAULT_STACK_SIZE
#define _THREAD2_STACK_SIZE _DEFAULT_STACK_SIZE
#define _THREAD3_STACK_SIZE _DEFAULT_STACK_SIZE
#define _THREAD4_STACK_SIZE _DEFAULT_STACK_SIZE
#define _THREAD5_STACK_SIZE _DEFAULT_STACK_SIZE
#define _THREAD6_STACK_SIZE _DEFAULT_STACK_SIZE
#define _THREAD7_STACK_SIZE _DEFAULT_STACK_SIZE
#define THREAD_PC_SHIFT 3
#define THREAD_R2 2
#define THREAD_R3 3
Functions
SXC_INLINE void thread_run (uint16_t thrd_num)
Starts running the selected thread. No effect if the thread is already running.
SXC_INLINE void thread_stop (uint16_t thrd_num)
Stops the selected thread. No effect if thread is already stopped.
SXC_INLINE void thread_stoprun_multiple (uint16_t thrds)
Stops/starts the execution of the selected threads. Multiple threads may be affected simultaneously. Setting bitN stops threadN, while clearing it starts/continues running the thread. It is not recommended to call this function, unless one knows the run status of all threads and preserves the status of threads which are not intended to be run or stopped by a call to this function.
SXC_INLINE uint16_t thread_getpage (void)
Returns the bit sequence indicating which I/O page every thread is using at the time of function call.
SXC_INLINE void thread_setup (void *(*func)(void *), void *ptr, uint16_t thrd_num)
Sets up initial arguments and initial function to execute in the selected thread. Does NOT actually start the thread. Behaviour is undefined if the thread is already executing.
SXC_INLINE void thread_return (void *value_p)
Writes the 16-bit return value pointed to by value_p to the top of the calling thread's stack, then stops execution of the thread.
SXC_INLINE uint16_t thread_read_retval (uint16_t thrd_num)
Returns the 16-bit value at the top of the stack of the target thread. Assuming that the thread called thread_return and was not restarted before calling this function, this will return the value that thread_return was called with; otherwise, the value is garbage.
Variables
static pthread_t p_thrds [kNumThrds]
uint16_t THREAD0_STACK []
uint16_t thrds_vector
Detailed Description
Provides a convenient interface for enabling multithreading on the XInC2. Thread-safe, but all threads are equal peers and may terminate each other's execution. Uses POSIX under-the-hood for other platforms: same interface as XInC2.
Definition in file Thread.h.
Macro Definition Documentation
#define _DEFAULT_STACK_SIZE 256
Definition at line 26 of file Thread.h.
Referenced by thread_read_retval(), and thread_return().
#define _THREAD0_STACK_SIZE _DEFAULT_STACK_SIZE
Definition at line 27 of file Thread.h.
#define _THREAD1_STACK_SIZE _DEFAULT_STACK_SIZE
Definition at line 28 of file Thread.h.
#define _THREAD2_STACK_SIZE _DEFAULT_STACK_SIZE
Definition at line 29 of file Thread.h.
#define _THREAD3_STACK_SIZE _DEFAULT_STACK_SIZE
Definition at line 30 of file Thread.h.
#define _THREAD4_STACK_SIZE _DEFAULT_STACK_SIZE
Definition at line 31 of file Thread.h.
#define _THREAD5_STACK_SIZE _DEFAULT_STACK_SIZE
Definition at line 32 of file Thread.h.
#define _THREAD6_STACK_SIZE _DEFAULT_STACK_SIZE
Definition at line 33 of file Thread.h.
#define _THREAD7_STACK_SIZE _DEFAULT_STACK_SIZE
Definition at line 34 of file Thread.h.
#define kNumThrds 8
Definition at line 17 of file Thread.h.
Referenced by thread_read_retval(), thread_run(), thread_setup(), and thread_stop().
#define THREAD_PC_SHIFT 3
Definition at line 36 of file Thread.h.
Referenced by thread_setup().
#define THREAD_R2 2
Definition at line 37 of file Thread.h.
Referenced by thread_setup().
#define THREAD_R3 3
Definition at line 38 of file Thread.h.
Function Documentation
SXC_INLINE uint16_t thread_getpage (void)
Returns the bit sequence indicating which I/O page every thread is using at the time of function call.
Returns
The 8-bit sequence representing which I/O page each thread is using. ex. if bit0 is 1, thread0 is using page1
Definition at line 101 of file Thread.h.
References SCUiopageRD.
 {
 #ifndef __XINC2__
 #else
   return _inp(SCUiopageRD);
 #endif
   return 0;
 }
SXC_INLINE uint16_t thread_read_retval (uint16_t thrd_num)
Returns the 16-bit value at the top of the stack of the target thread. Assuming that the thread called thread_return and was not restarted before calling this function, this will return the value that thread_return was called with; otherwise, the value is garbage.
Parameters
[in] thrd_num Thread whose return value to read
Returns
The 16-bit value at the top of the stack of the target thread
Definition at line 159 of file Thread.h.
References _DEFAULT_STACK_SIZE, kNumThrds, safe_mode_assert, sem_lock(), SEM_THRD, sem_unlock(), and THREAD0_STACK.
 {
   safe_mode_assert(thrd_num < kNumThrds);
   sem_lock(SEM_THRD);
   // This will fall apart if the stacks are not all the same size
   uint16_t retval = THREAD0_STACK[thrd_num*_DEFAULT_STACK_SIZE];
   sem_unlock(SEM_THRD);
   return retval;
 }
SXC_INLINE void thread_return (void * value_p)
Writes the 16-bit return value pointed to by value_p to the top of the calling thread's stack, then stops execution of the thread.
Parameters
[in] value_p pointer to desired return value
Definition at line 137 of file Thread.h.
References _DEFAULT_STACK_SIZE, THREAD0_STACK, and thread_stop().
 {
 #ifndef __XINC2__
   pthread_t thrd_num = pthread_self();
 #else
   uint16_t thrd_num = _thrd();
   // This will fall apart if the stacks are not all the same size
   uint16_t* stack_top = THREAD0_STACK + thrd_num*_DEFAULT_STACK_SIZE;
   *stack_top = *(uint16_t*)value_p;
 #endif
   thread_stop(thrd_num);
   return;
 }
SXC_INLINE void thread_run (uint16_t thrd_num)
Starts running the selected thread. No effect if the thread is already running.
Parameters
[in] thrd_num 3-bit integer representing which thread to run.
Definition at line 45 of file Thread.h.
References kNumThrds, safe_mode_assert, SCUstop, sem_lock(), SEM_THRD, sem_unlock(), and thrds_vector.
 {
   safe_mode_assert(thrd_num < kNumThrds);
   sem_lock(SEM_THRD);
   thrds_vector &= ~(1 << thrd_num);
 #ifndef __XINC2__
 #else
   _outp(thrds_vector, SCUstop);
 #endif
   sem_unlock(SEM_THRD);
 }
SXC_INLINE void thread_setup (void *(*)(void *) func, void * ptr, uint16_t thrd_num)
Sets up initial arguments and initial function to execute in the selected thread. Does NOT actually start the thread. Behaviour is undefined if the thread is already executing.
Parameters
[in] func Function pointer to the input function. Function may have no return value and no inputs, or pointers for either or both.
[in] ptr Pointer to input arguments to provide to thread function.
[in] thrd_num The thread to set up.
Definition at line 119 of file Thread.h.
References kNumThrds, safe_mode_assert, SCUpc, SCUpntr, SCUreg, sem_lock(), SEM_THRD, sem_unlock(), THREAD_PC_SHIFT, and THREAD_R2.
 {
   safe_mode_assert(thrd_num < kNumThrds);
   sem_lock(SEM_THRD);
 #ifndef __XINC2__
 #else
   _outp((thrd_num << THREAD_PC_SHIFT)|THREAD_R2, SCUpntr);
   _outp((uint16_t)ptr, SCUreg);
   _outp((uint16_t)func, SCUpc);
 #endif
   sem_unlock(SEM_THRD);
 }
SXC_INLINE void thread_stop (uint16_t thrd_num)
Stops the selected thread. No effect if thread is already stopped.
Parameters
[in] thrd_num 3-bit integer representing which thread to stop.
Definition at line 62 of file Thread.h.
References kNumThrds, safe_mode_assert, SCUstop, sem_lock(), SEM_THRD, sem_unlock(), and thrds_vector.
Referenced by thread_return().
 {
   safe_mode_assert(thrd_num < kNumThrds);
   sem_lock(SEM_THRD);
   thrds_vector |= (1 << thrd_num);
 #ifndef __XINC2__
 #else
   _outp(thrds_vector, SCUstop);
 #endif
   sem_unlock(SEM_THRD);
 }
SXC_INLINE void thread_stoprun_multiple (uint16_t thrds)
Stops/starts the execution of the selected threads. Multiple threads may be affected simultaneously. Setting bitN stops threadN, while clearing it starts/continues running the thread. It is not recommended to call this function, unless one knows the run status of all threads and preserves the status of threads which are not intended to be run or stopped by a call to this function.
Parameters
[in] thrds Lower byte: set bits correspond to threads to stop, cleared bits correspond to threads to run. Upper byte is irrelevant.
Definition at line 84 of file Thread.h.
References SCUstop, sem_lock(), SEM_THRD, sem_unlock(), and thrds_vector.
 {
   sem_lock(SEM_THRD);
 #ifndef __XINC2__
 #else
   thrds_vector = thrds;
   _outp(thrds_vector, SCUstop);
 #endif
   sem_unlock(SEM_THRD);
 }
Variable Documentation
pthread_t p_thrds[kNumThrds] static
Definition at line 21 of file Thread.h.
uint16_t thrds_vector
Referenced by thread_run(), thread_stop(), and thread_stoprun_multiple().
uint16_t THREAD0_STACK[]
Referenced by thread_read_retval(), and thread_return().