sxc-lib: UART.h File Reference
UART.h File Reference
Convenience functions and implementation using 2 arbitrary GPIO pins in order to utilize a UART protocol.
#include "SXC.h"
#include "SFU.h"
#include "GPIO.h"
#include "SystemClock.h"
#include "Structs.h"
Data Structures
struct UART_Pin_Pair
Typedefs
typedef struct UART_Pin_Pair UART_Pin_Pair
Functions
SXC_INLINE void uart_write_byte (uint16_t byte, UART_Pin_Pair const *pins)
Transmits the LSB of the input word as a byte over a UART tx pin.
SXC_INLINE uint16_t uart_read_byte (UART_Pin_Pair const *pins)
Reads an 8-bit byte from the rx pin of a UART pair.
SXC_INLINE void uart_write_buf (uint16_t *buf, size_t len, UART_Pin_Pair const *pins)
Transmits the LSBs of an array of input words over a UART tx pin.
Detailed Description
Convenience functions and implementation using 2 arbitrary GPIO pins in order to utilize a UART protocol.
Definition in file UART.h.
Typedef Documentation
typedef struct UART_Pin_Pair UART_Pin_Pair
Function Documentation
SXC_INLINE uint16_t uart_read_byte (UART_Pin_Pair const * pins)
Reads an 8-bit byte from the rx pin of a UART pair.
Parameters
[in] pins Pointer to the UART_Pin_Pair of interest
Returns
8-bit byte read from the UART rx, in the LSB of a 16-bit word
Definition at line 51 of file UART.h.
References globalPin_read_raw(), UART_Pin_Pair::rx, sys_clock_wait(), and UART_Pin_Pair::timeout.
 {
   uint16_t byte = 0;
   while(globalPin_read_raw(&pins->rx)); //wait until the start bit is written (0)
   sys_clock_wait(pins->timeout);
   //Read bits, starting with lsb
   for (int16_t i = 0; i <= 7; ++i) {
     byte += _rol(globalPin_read_raw(&pins->rx), i);
     sys_clock_wait(pins->timeout);
   }
   while(!globalPin_read_raw(&pins->rx)); //wait until stop bit is written (1)
   return byte;
 }
SXC_INLINE void uart_write_buf (uint16_t * buf, size_t len, UART_Pin_Pair const * pins)
Transmits the LSBs of an array of input words over a UART tx pin.
Parameters
[in] buf Array of 16-bit words whose LSBs are written. MSBs are ignored.
[in] len Length of the array (number of bytes to write)
[in] pins Pointer to the UART_Pin_Pair of interest
Definition at line 71 of file UART.h.
References uart_write_byte().
 {
   for (size_t i = 0; i < len; ++i)
     uart_write_byte(buf[i], pins);
 }
SXC_INLINE void uart_write_byte (uint16_t byte, UART_Pin_Pair const * pins)
Transmits the LSB of the input word as a byte over a UART tx pin.
Parameters
[in] byte 16-bit word whose LSB is transmitted. MSB is ignored.
[in] pins Pointer to the UART_Pin_Pair of interest
Definition at line 30 of file UART.h.
References globalPin_write_raw(), sys_clock_wait(), UART_Pin_Pair::timeout, and UART_Pin_Pair::tx.
Referenced by uart_write_buf().
 {
   globalPin_write_raw(0, &pins->tx); //write the start bit
   sys_clock_wait(pins->timeout);
   //Write bits, starting with lsb
   for (int16_t i = 0; i <= 7; ++i) {
     if (_rol(1, i) & byte)
       globalPin_write_raw(1, &pins->tx);
     else
       globalPin_write_raw(0, &pins->tx);
     sys_clock_wait(pins->timeout);
   }
   globalPin_write_raw(1, &pins->tx); //write the stop bit
   sys_clock_wait(pins->timeout);
 }