sxc-lib: Varactor.h File Reference
Varactor.h File Reference
Interface for utilizing the varactor to adjust crystal resonant frequency. Utilizes timer B to do so, will need semaphore protection.
#include "SystemClock.h"
Macros
#define VARACTOR_UP_VALUE 450
#define VARACTOR_DOWN_VALUE 50
Functions
SXC_INLINE uint16_t get_tmrbcfg (enum sys_freq sf)
SXC_INLINE void varactor_setup (enum sys_freq sf)
SXC_INLINE void varactor_pull_up (void)
SXC_INLINE void varactor_pull_down (void)
Detailed Description
Interface for utilizing the varactor to adjust crystal resonant frequency. Utilizes timer B to do so, will need semaphore protection.
Definition in file Varactor.h.
Macro Definition Documentation
#define VARACTOR_DOWN_VALUE 50
Definition at line 15 of file Varactor.h.
Referenced by varactor_pull_down().
#define VARACTOR_UP_VALUE 450
Definition at line 14 of file Varactor.h.
Referenced by varactor_pull_up().
Function Documentation
SXC_INLINE uint16_t get_tmrbcfg (enum sys_freq sf)
Definition at line 17 of file Varactor.h.
References _110_592_MHz, _12_288_MHz, _24_576_MHz, _36_864_MHz, _49_152_MHz, _73_728_MHz, _98_304_MHz, TIMER_CLOCK_RATE_4, TIMER_CLOCK_RATE_8, TIMER_ENABLE, and TIMER_MODE_UP.
Referenced by varactor_setup().
 {
   switch(sf) {
   case _12_288_MHz:
     return TIMER_ENABLE|TIMER_MODE_UP;
   case _24_576_MHz:
     return TIMER_ENABLE|TIMER_MODE_UP;
   case _36_864_MHz:
     return TIMER_ENABLE|TIMER_MODE_UP;
   case _49_152_MHz:
     return TIMER_ENABLE|TIMER_MODE_UP|TIMER_CLOCK_RATE_4;
   case _73_728_MHz:
     return TIMER_ENABLE|TIMER_MODE_UP|TIMER_CLOCK_RATE_4;
   case _98_304_MHz:
     return TIMER_ENABLE|TIMER_MODE_UP|TIMER_CLOCK_RATE_8;
   case _110_592_MHz:
     return TIMER_ENABLE|TIMER_MODE_UP|TIMER_CLOCK_RATE_8;
   default:
     return 0;
   }
 }
SXC_INLINE void varactor_pull_down (void)
Definition at line 56 of file Varactor.h.
References TIMER_B, timer_write_CCR(), and VARACTOR_DOWN_VALUE.
 {
   timer_write_CCR(VARACTOR_DOWN_VALUE, 1, TIMER_B);
 }
SXC_INLINE void varactor_pull_up (void)
Definition at line 51 of file Varactor.h.
References TIMER_B, timer_write_CCR(), and VARACTOR_UP_VALUE.
 {
   timer_write_CCR(VARACTOR_UP_VALUE, 1, TIMER_B);
 }
SXC_INLINE void varactor_setup (enum sys_freq sf)
Definition at line 39 of file Varactor.h.
References get_tmrbcfg(), TIMER_B, TIMER_CCM_CMP_OUT_EQ_1, TIMER_CCM_COMP_NOT_CAP, TIMER_CCM_OUT_ENABLE, TIMER_CCM_OUTPUT_RESET_SET, timer_set_config(), timer_set_config_ccm(), and timer_write_CCR().
 {
   //The 0x1 should do nothing (read-only bit), but it was there in the original
   timer_set_config_ccm(
     0x1 | TIMER_CCM_COMP_NOT_CAP | TIMER_CCM_CMP_OUT_EQ_1 | TIMER_CCM_OUT_ENABLE
     | TIMER_CCM_OUTPUT_RESET_SET, 1, TIMER_B
   );
   timer_write_CCR(500, 0, TIMER_B); //why 500? nfi
   timer_write_CCR(190, 1, TIMER_B); //why 190? nfi
   timer_set_config(get_tmrbcfg(sf), TIMER_B);
 }